/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type ManageAssetAndSharesStruct = {
  yToken: AddressLike;
  shares: BigNumberish;
  assetAmount: BigNumberish;
  updateAsset: boolean;
  isMint: boolean;
};

export type ManageAssetAndSharesStructOutput = [
  yToken: string,
  shares: bigint,
  assetAmount: bigint,
  updateAsset: boolean,
  isMint: boolean,
] & {
  yToken: string;
  shares: bigint;
  assetAmount: bigint;
  updateAsset: boolean;
  isMint: boolean;
};

export interface ManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "depositAssets"
      | "redeem"
      | "withdrawAssets",
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "OrderRequest"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "administrator",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "custodyWallets",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "depositAssets",
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "executeOrder",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "guardrailPercentageForAsset",
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [AddressLike, AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "manageAssetAndShares",
    values: [AddressLike, ManageAssetAndSharesStruct],
  ): string;
  encodeFunctionData(
    functionFragment: "minSharesInYToken",
    values: [AddressLike],
  ): string;
  encodeFunctionData(functionFragment: "receipt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "setAdministrator",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "setAsset",
    values: [boolean, AddressLike, AddressLike, BigNumberish, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: "setCustodyWallet",
    values: [AddressLike, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: "setMinSharesInYToken",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setReceipt",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "transferToCustodyWallet",
    values: [AddressLike, AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawAssets",
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBondYield",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike],
  ): string;

  decodeFunctionResult(
    functionFragment: "administrator",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "custodyWallets",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositAssets",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOrder",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardrailPercentageForAsset",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manageAssetAndShares",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "minSharesInYToken",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "receipt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAdministrator",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "setAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCustodyWallet",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinSharesInYToken",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "setReceipt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToCustodyWallet",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAssets",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBondYield",
    data: BytesLike,
  ): Result;
}

export namespace AdministratorSetEvent {
  export type InputTuple = [caller: AddressLike, newAdministrator: AddressLike];
  export type OutputTuple = [caller: string, newAdministrator: string];
  export interface OutputObject {
    caller: string;
    newAdministrator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetAndShareManagedEvent {
  export type InputTuple = [
    caller: AddressLike,
    yToken: AddressLike,
    shares: BigNumberish,
    assetAmount: BigNumberish,
    updateAsset: boolean,
    isMint: boolean,
  ];
  export type OutputTuple = [
    caller: string,
    yToken: string,
    shares: bigint,
    assetAmount: bigint,
    updateAsset: boolean,
    isMint: boolean,
  ];
  export interface OutputObject {
    caller: string;
    yToken: string;
    shares: bigint;
    assetAmount: bigint;
    updateAsset: boolean;
    isMint: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetStatusEvent {
  export type InputTuple = [
    orderType: boolean,
    yToken: AddressLike,
    asset: AddressLike,
    status: boolean,
  ];
  export type OutputTuple = [
    orderType: boolean,
    yToken: string,
    asset: string,
    status: boolean,
  ];
  export interface OutputObject {
    orderType: boolean;
    yToken: string;
    asset: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustodyWalletSetEvent {
  export type InputTuple = [
    caller: AddressLike,
    wallet: AddressLike,
    status: boolean,
  ];
  export type OutputTuple = [caller: string, wallet: string, status: boolean];
  export interface OutputObject {
    caller: string;
    wallet: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    caller: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    receiver: AddressLike,
    yToken: AddressLike,
    shares: BigNumberish,
    feeShare: BigNumberish,
    gasFeeShare: BigNumberish,
  ];
  export type OutputTuple = [
    caller: string,
    asset: string,
    amount: bigint,
    receiver: string,
    yToken: string,
    shares: bigint,
    feeShare: bigint,
    gasFeeShare: bigint,
  ];
  export interface OutputObject {
    caller: string;
    asset: string;
    amount: bigint;
    receiver: string;
    yToken: string;
    shares: bigint;
    feeShare: bigint;
    gasFeeShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinSharesInYTokenSetEvent {
  export type InputTuple = [
    caller: AddressLike,
    yToken: AddressLike,
    minShares: BigNumberish,
  ];
  export type OutputTuple = [caller: string, yToken: string, minShares: bigint];
  export interface OutputObject {
    caller: string;
    yToken: string;
    minShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderRequestEvent {
  export type InputTuple = [
    caller: AddressLike,
    yToken: AddressLike,
    asset: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    orderType: boolean,
    exchangeRateInUnderlying: BigNumberish,
    receiptId: BigNumberish,
    referralCode: BytesLike,
  ];
  export type OutputTuple = [
    caller: string,
    yToken: string,
    asset: string,
    receiver: string,
    amount: bigint,
    orderType: boolean,
    exchangeRateInUnderlying: bigint,
    receiptId: bigint,
    referralCode: string,
  ];
  export interface OutputObject {
    caller: string;
    yToken: string;
    asset: string;
    receiver: string;
    amount: bigint;
    orderType: boolean;
    exchangeRateInUnderlying: bigint;
    receiptId: bigint;
    referralCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptSetEvent {
  export type InputTuple = [caller: AddressLike, receipt: AddressLike];
  export type OutputTuple = [caller: string, receipt: string];
  export interface OutputObject {
    caller: string;
    receipt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RescueEvent {
  export type InputTuple = [
    caller: AddressLike,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
  ];
  export type OutputTuple = [
    caller: string,
    token: string,
    to: string,
    amount: bigint,
  ];
  export interface OutputObject {
    caller: string;
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySetEvent {
  export type InputTuple = [caller: AddressLike, treasury: AddressLike];
  export type OutputTuple = [caller: string, treasury: string];
  export interface OutputObject {
    caller: string;
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [
    caller: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    receiver: AddressLike,
    yToken: AddressLike,
    shares: BigNumberish,
    feeShare: BigNumberish,
    gasFeeShare: BigNumberish,
  ];
  export type OutputTuple = [
    caller: string,
    asset: string,
    amount: bigint,
    receiver: string,
    yToken: string,
    shares: bigint,
    feeShare: bigint,
    gasFeeShare: bigint,
  ];
  export interface OutputObject {
    caller: string;
    asset: string;
    amount: bigint;
    receiver: string;
    yToken: string;
    shares: bigint;
    feeShare: bigint;
    gasFeeShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldFeesTransferredEvent {
  export type InputTuple = [
    treasury: AddressLike,
    yToken: AddressLike,
    shares: BigNumberish,
  ];
  export type OutputTuple = [treasury: string, yToken: string, shares: bigint];
  export interface OutputObject {
    treasury: string;
    yToken: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Manager extends BaseContract {
  connect(runner?: ContractRunner | null): Manager;
  waitForDeployment(): Promise<this>;

  interface: ManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  administrator: TypedContractMethod<[], [string], "view">;

  custodyWallets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  deposit: TypedContractMethod<
    [
      _yToken: AddressLike,
      _asset: AddressLike,
      _amount: BigNumberish,
      _receiver: AddressLike,
      _callback: AddressLike,
      _callbackData: BytesLike,
      _referralCode: BytesLike,
    ],
    [void],
    "nonpayable"
  >;

  depositAssets: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  executeOrder: TypedContractMethod<
    [
      _receiptId: BigNumberish,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _gas: BigNumberish,
    ],
    [void],
    "nonpayable"
  >;

  guardrailPercentageForAsset: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  init: TypedContractMethod<
    [
      _administrator: AddressLike,
      _treasury: AddressLike,
      _receipt: AddressLike,
    ],
    [void],
    "nonpayable"
  >;

  manageAssetAndShares: TypedContractMethod<
    [_to: AddressLike, _order: ManageAssetAndSharesStruct],
    [void],
    "nonpayable"
  >;

  minSharesInYToken: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  receipt: TypedContractMethod<[], [string], "view">;

  redeem: TypedContractMethod<
    [
      caller: AddressLike,
      _yToken: AddressLike,
      _asset: AddressLike,
      _shares: BigNumberish,
      _receiver: AddressLike,
      _callback: AddressLike,
      _callbackData: BytesLike,
    ],
    [void],
    "nonpayable"
  >;

  setAdministrator: TypedContractMethod<
    [_administrator: AddressLike],
    [void],
    "nonpayable"
  >;

  setAsset: TypedContractMethod<
    [
      _orderType: boolean,
      _yToken: AddressLike,
      _asset: AddressLike,
      _guardrailPercentage: BigNumberish,
      _status: boolean,
    ],
    [void],
    "nonpayable"
  >;

  setCustodyWallet: TypedContractMethod<
    [_wallet: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  setMinSharesInYToken: TypedContractMethod<
    [_yToken: AddressLike, _minShares: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReceipt: TypedContractMethod<
    [_receipt: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferToCustodyWallet: TypedContractMethod<
    [_token: AddressLike, _receiver: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  withdrawAssets: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  withdrawBondYield: TypedContractMethod<
    [
      _yToken: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      assetToken: AddressLike,
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "administrator",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "custodyWallets",
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposit",
  ): TypedContractMethod<
    [
      _yToken: AddressLike,
      _asset: AddressLike,
      _amount: BigNumberish,
      _receiver: AddressLike,
      _callback: AddressLike,
      _callbackData: BytesLike,
      _referralCode: BytesLike,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositAssets",
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeOrder",
  ): TypedContractMethod<
    [
      _receiptId: BigNumberish,
      _amount: BigNumberish,
      _fee: BigNumberish,
      _gas: BigNumberish,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "guardrailPercentageForAsset",
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "init",
  ): TypedContractMethod<
    [
      _administrator: AddressLike,
      _treasury: AddressLike,
      _receipt: AddressLike,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "manageAssetAndShares",
  ): TypedContractMethod<
    [_to: AddressLike, _order: ManageAssetAndSharesStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minSharesInYToken",
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "receipt",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeem",
  ): TypedContractMethod<
    [
      caller: AddressLike,
      _yToken: AddressLike,
      _asset: AddressLike,
      _shares: BigNumberish,
      _receiver: AddressLike,
      _callback: AddressLike,
      _callbackData: BytesLike,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdministrator",
  ): TypedContractMethod<[_administrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAsset",
  ): TypedContractMethod<
    [
      _orderType: boolean,
      _yToken: AddressLike,
      _asset: AddressLike,
      _guardrailPercentage: BigNumberish,
      _status: boolean,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCustodyWallet",
  ): TypedContractMethod<
    [_wallet: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinSharesInYToken",
  ): TypedContractMethod<
    [_yToken: AddressLike, _minShares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReceipt",
  ): TypedContractMethod<[_receipt: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury",
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferToCustodyWallet",
  ): TypedContractMethod<
    [_token: AddressLike, _receiver: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "treasury",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawAssets",
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawBondYield",
  ): TypedContractMethod<
    [
      _yToken: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      assetToken: AddressLike,
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdministratorSet",
  ): TypedContractEvent<
    AdministratorSetEvent.InputTuple,
    AdministratorSetEvent.OutputTuple,
    AdministratorSetEvent.OutputObject
  >;
  getEvent(
    key: "AssetAndShareManaged",
  ): TypedContractEvent<
    AssetAndShareManagedEvent.InputTuple,
    AssetAndShareManagedEvent.OutputTuple,
    AssetAndShareManagedEvent.OutputObject
  >;
  getEvent(
    key: "AssetStatus",
  ): TypedContractEvent<
    AssetStatusEvent.InputTuple,
    AssetStatusEvent.OutputTuple,
    AssetStatusEvent.OutputObject
  >;
  getEvent(
    key: "CustodyWalletSet",
  ): TypedContractEvent<
    CustodyWalletSetEvent.InputTuple,
    CustodyWalletSetEvent.OutputTuple,
    CustodyWalletSetEvent.OutputObject
  >;
  getEvent(
    key: "Deposit",
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Initialized",
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MinSharesInYTokenSet",
  ): TypedContractEvent<
    MinSharesInYTokenSetEvent.InputTuple,
    MinSharesInYTokenSetEvent.OutputTuple,
    MinSharesInYTokenSetEvent.OutputObject
  >;
  getEvent(
    key: "OrderRequest",
  ): TypedContractEvent<
    OrderRequestEvent.InputTuple,
    OrderRequestEvent.OutputTuple,
    OrderRequestEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptSet",
  ): TypedContractEvent<
    ReceiptSetEvent.InputTuple,
    ReceiptSetEvent.OutputTuple,
    ReceiptSetEvent.OutputObject
  >;
  getEvent(
    key: "Rescue",
  ): TypedContractEvent<
    RescueEvent.InputTuple,
    RescueEvent.OutputTuple,
    RescueEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySet",
  ): TypedContractEvent<
    TreasurySetEvent.InputTuple,
    TreasurySetEvent.OutputTuple,
    TreasurySetEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw",
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;
  getEvent(
    key: "YieldFeesTransferred",
  ): TypedContractEvent<
    YieldFeesTransferredEvent.InputTuple,
    YieldFeesTransferredEvent.OutputTuple,
    YieldFeesTransferredEvent.OutputObject
  >;

  filters: {
    "AdministratorSet(address,address)": TypedContractEvent<
      AdministratorSetEvent.InputTuple,
      AdministratorSetEvent.OutputTuple,
      AdministratorSetEvent.OutputObject
    >;
    AdministratorSet: TypedContractEvent<
      AdministratorSetEvent.InputTuple,
      AdministratorSetEvent.OutputTuple,
      AdministratorSetEvent.OutputObject
    >;

    "AssetAndShareManaged(address,address,uint256,uint256,bool,bool)": TypedContractEvent<
      AssetAndShareManagedEvent.InputTuple,
      AssetAndShareManagedEvent.OutputTuple,
      AssetAndShareManagedEvent.OutputObject
    >;
    AssetAndShareManaged: TypedContractEvent<
      AssetAndShareManagedEvent.InputTuple,
      AssetAndShareManagedEvent.OutputTuple,
      AssetAndShareManagedEvent.OutputObject
    >;

    "AssetStatus(bool,address,address,bool)": TypedContractEvent<
      AssetStatusEvent.InputTuple,
      AssetStatusEvent.OutputTuple,
      AssetStatusEvent.OutputObject
    >;
    AssetStatus: TypedContractEvent<
      AssetStatusEvent.InputTuple,
      AssetStatusEvent.OutputTuple,
      AssetStatusEvent.OutputObject
    >;

    "CustodyWalletSet(address,address,bool)": TypedContractEvent<
      CustodyWalletSetEvent.InputTuple,
      CustodyWalletSetEvent.OutputTuple,
      CustodyWalletSetEvent.OutputObject
    >;
    CustodyWalletSet: TypedContractEvent<
      CustodyWalletSetEvent.InputTuple,
      CustodyWalletSetEvent.OutputTuple,
      CustodyWalletSetEvent.OutputObject
    >;

    "Deposit(address,address,uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MinSharesInYTokenSet(address,address,uint256)": TypedContractEvent<
      MinSharesInYTokenSetEvent.InputTuple,
      MinSharesInYTokenSetEvent.OutputTuple,
      MinSharesInYTokenSetEvent.OutputObject
    >;
    MinSharesInYTokenSet: TypedContractEvent<
      MinSharesInYTokenSetEvent.InputTuple,
      MinSharesInYTokenSetEvent.OutputTuple,
      MinSharesInYTokenSetEvent.OutputObject
    >;

    "OrderRequest(address,address,address,address,uint256,bool,uint256,uint256,bytes32)": TypedContractEvent<
      OrderRequestEvent.InputTuple,
      OrderRequestEvent.OutputTuple,
      OrderRequestEvent.OutputObject
    >;
    OrderRequest: TypedContractEvent<
      OrderRequestEvent.InputTuple,
      OrderRequestEvent.OutputTuple,
      OrderRequestEvent.OutputObject
    >;

    "ReceiptSet(address,address)": TypedContractEvent<
      ReceiptSetEvent.InputTuple,
      ReceiptSetEvent.OutputTuple,
      ReceiptSetEvent.OutputObject
    >;
    ReceiptSet: TypedContractEvent<
      ReceiptSetEvent.InputTuple,
      ReceiptSetEvent.OutputTuple,
      ReceiptSetEvent.OutputObject
    >;

    "Rescue(address,address,address,uint256)": TypedContractEvent<
      RescueEvent.InputTuple,
      RescueEvent.OutputTuple,
      RescueEvent.OutputObject
    >;
    Rescue: TypedContractEvent<
      RescueEvent.InputTuple,
      RescueEvent.OutputTuple,
      RescueEvent.OutputObject
    >;

    "TreasurySet(address,address)": TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
    TreasurySet: TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;

    "Withdraw(address,address,uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;

    "YieldFeesTransferred(address,address,uint256)": TypedContractEvent<
      YieldFeesTransferredEvent.InputTuple,
      YieldFeesTransferredEvent.OutputTuple,
      YieldFeesTransferredEvent.OutputObject
    >;
    YieldFeesTransferred: TypedContractEvent<
      YieldFeesTransferredEvent.InputTuple,
      YieldFeesTransferredEvent.OutputTuple,
      YieldFeesTransferredEvent.OutputObject
    >;
  };
}
