/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumberish,
    BytesLike,
    FunctionFragment,
    Result,
    Interface,
    EventFragment,
    AddressLike,
    ContractRunner,
    ContractMethod,
} from "ethers";
import type {
    TypedContractMethod,
} from "../common";

export interface VyTokenInterface extends Interface {
    getFunction(
        nameOrSignature:
            | "allowance"
            | "approve"
            | "asset"
            | "balanceOf"
            | "convertToAssets"
            | "convertToShares"
            | "decimals"
            | "deposit"
            | "depositYToken"
            | "maxDeposit"
            | "maxMint"
            | "maxRedeem"
            | "maxWithdraw"
            | "name"
            | "previewDeposit"
            | "previewMint"
            | "previewRedeem"
            | "previewWithdraw"
            | "redeem"
            | "symbol"
            | "totalAssets"
            | "totalSupply"
            | "transfer"
            | "transferFrom"
            | "withdraw"
            | "yToken"
    ): FunctionFragment;

    getEvent(
        nameOrSignatureOrTopic:
            | "Approval"
            | "Deposit"
            | "GuardrailMultiplierSet"
            | "Transfer"
            | "Withdraw"
            | "YTokenSet"
    ): EventFragment;

    encodeFunctionData(
        functionFragment: "allowance",
        values: [AddressLike, AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "approve",
        values: [AddressLike, BigNumberish]
    ): string;
    encodeFunctionData(functionFragment: "asset", values?: undefined): string;
    encodeFunctionData(
        functionFragment: "balanceOf",
        values: [AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "convertToAssets",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "convertToShares",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
    encodeFunctionData(
        functionFragment: "deposit",
        values: [BigNumberish, AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "depositYToken",
        values: [AddressLike, BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "guardrailMultiplier",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "maxDeposit",
        values: [AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "maxMint",
        values: [AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "maxRedeem",
        values: [AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "maxWithdraw",
        values: [AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "mint",
        values: [BigNumberish, AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "mintYToken",
        values: [AddressLike, BigNumberish, boolean]
    ): string;
    encodeFunctionData(functionFragment: "name", values?: undefined): string;
    encodeFunctionData(
        functionFragment: "previewDeposit",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "previewMint",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "previewRedeem",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "previewWithdraw",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "redeem",
        values: [BigNumberish, AddressLike, AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "setGuardrailMultiplier",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "setStrategy",
        values: [AddressLike, boolean]
    ): string;
    encodeFunctionData(
        functionFragment: "setYTokenAndAllowance",
        values: [AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "sendToStrategy",
        values: [AddressLike, BigNumberish, AddressLike]
    ): string;
    encodeFunctionData(
        functionFragment: "strategyAddress",
        values: [AddressLike]
    ): string;
    encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
    encodeFunctionData(
        functionFragment: "totalAssets",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "totalSupply",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "transfer",
        values: [AddressLike, BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "transferFrom",
        values: [AddressLike, AddressLike, BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "withdraw",
        values: [BigNumberish, AddressLike, AddressLike]
    ): string;
    encodeFunctionData(functionFragment: "yToken", values?: undefined): string;

    decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "convertToAssets",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "convertToShares",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "depositYToken",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "guardrailMultiplier",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "maxDeposit", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "maxMint", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "maxRedeem", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "maxWithdraw",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "mintYToken", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "previewDeposit",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "previewMint",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "previewRedeem",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "previewWithdraw",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "setGuardrailMultiplier",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "setStrategy",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "setYTokenAndAllowance",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "sendToStrategy",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "strategyAddress",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "totalAssets",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "totalSupply",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "transferFrom",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "yToken", data: BytesLike): Result;
}

export interface VyToken extends BaseContract {
    connect(runner?: ContractRunner | null): VyToken;
    waitForDeployment(): Promise<this>;

    interface: VyTokenInterface;

    // Read-only methods
    allowance: TypedContractMethod<
        [owner: AddressLike, spender: AddressLike],
        [bigint],
        "view"
    >;
    asset: TypedContractMethod<[], [string], "view">;
    balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;
    convertToAssets: TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
    convertToShares: TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
    decimals: TypedContractMethod<[], [bigint], "view">;
    guardrailMultiplier: TypedContractMethod<[], [bigint], "view">;
    maxDeposit: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
    maxMint: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
    maxRedeem: TypedContractMethod<[owner: AddressLike], [bigint], "view">;
    maxWithdraw: TypedContractMethod<[owner: AddressLike], [bigint], "view">;
    name: TypedContractMethod<[], [string], "view">;
    previewDeposit: TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
    previewMint: TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
    previewRedeem: TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
    previewWithdraw: TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
    strategyAddress: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
    symbol: TypedContractMethod<[], [string], "view">;
    totalAssets: TypedContractMethod<[], [bigint], "view">;
    totalSupply: TypedContractMethod<[], [bigint], "view">;
    yToken: TypedContractMethod<[], [string], "view">;

    // State-changing methods
    approve: TypedContractMethod<
        [spender: AddressLike, value: BigNumberish],
        [boolean],
        "nonpayable"
    >;
    deposit: TypedContractMethod<
        [assets: BigNumberish, receiver: AddressLike],
        [bigint],
        "nonpayable"
    >;
    depositYToken: TypedContractMethod<
        [to: AddressLike, amountYToken: BigNumberish],
        [void],
        "nonpayable"
    >;
    mint: TypedContractMethod<
        [shares: BigNumberish, receiver: AddressLike],
        [bigint],
        "nonpayable"
    >;
    mintYToken: TypedContractMethod<
        [to: AddressLike, shares: BigNumberish, isNewYToken: boolean],
        [void],
        "nonpayable"
    >;
    redeem: TypedContractMethod<
        [shares: BigNumberish, receiver: AddressLike, owner: AddressLike],
        [bigint],
        "nonpayable"
    >;
    setGuardrailMultiplier: TypedContractMethod<
        [_guardrailMultiplier: BigNumberish],
        [void],
        "nonpayable"
    >;
    setStrategy: TypedContractMethod<
        [_strategy: AddressLike, _status: boolean],
        [void],
        "nonpayable"
    >;
    setYTokenAndAllowance: TypedContractMethod<
        [_yToken: AddressLike],
        [void],
        "nonpayable"
    >;
    sendToStrategy: TypedContractMethod<
        [token: AddressLike, amount: BigNumberish, strategy: AddressLike],
        [void],
        "nonpayable"
    >;
    transfer: TypedContractMethod<
        [to: AddressLike, value: BigNumberish],
        [boolean],
        "nonpayable"
    >;
    transferFrom: TypedContractMethod<
        [from: AddressLike, to: AddressLike, value: BigNumberish],
        [boolean],
        "nonpayable"
    >;
    withdraw: TypedContractMethod<
        [assets: BigNumberish, receiver: AddressLike, owner: AddressLike],
        [bigint],
        "nonpayable"
    >;

    getFunction<T extends ContractMethod = ContractMethod>(
        key: string | FunctionFragment
    ): T;

    getFunction(
        nameOrSignature: "allowance"
    ): TypedContractMethod<
        [owner: AddressLike, spender: AddressLike],
        [bigint],
        "view"
    >;
    getFunction(
        nameOrSignature: "approve"
    ): TypedContractMethod<
        [spender: AddressLike, value: BigNumberish],
        [boolean],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "asset"
    ): TypedContractMethod<[], [string], "view">;
    getFunction(
        nameOrSignature: "balanceOf"
    ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
    getFunction(
        nameOrSignature: "convertToAssets"
    ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
    getFunction(
        nameOrSignature: "convertToShares"
    ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
    getFunction(
        nameOrSignature: "decimals"
    ): TypedContractMethod<[], [bigint], "view">;
    getFunction(
        nameOrSignature: "deposit"
    ): TypedContractMethod<
        [assets: BigNumberish, receiver: AddressLike],
        [bigint],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "depositYToken"
    ): TypedContractMethod<
        [to: AddressLike, amountYToken: BigNumberish],
        [void],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "guardrailMultiplier"
    ): TypedContractMethod<[], [bigint], "view">;
    getFunction(
        nameOrSignature: "maxDeposit"
    ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
    getFunction(
        nameOrSignature: "maxMint"
    ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
    getFunction(
        nameOrSignature: "maxRedeem"
    ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
    getFunction(
        nameOrSignature: "maxWithdraw"
    ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
    getFunction(
        nameOrSignature: "mint"
    ): TypedContractMethod<
        [shares: BigNumberish, receiver: AddressLike],
        [bigint],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "mintYToken"
    ): TypedContractMethod<
        [to: AddressLike, shares: BigNumberish, isNewYToken: boolean],
        [void],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "name"
    ): TypedContractMethod<[], [string], "view">;
    getFunction(
        nameOrSignature: "previewDeposit"
    ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
    getFunction(
        nameOrSignature: "previewMint"
    ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
    getFunction(
        nameOrSignature: "previewRedeem"
    ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
    getFunction(
        nameOrSignature: "previewWithdraw"
    ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
    getFunction(
        nameOrSignature: "redeem"
    ): TypedContractMethod<
        [shares: BigNumberish, receiver: AddressLike, owner: AddressLike],
        [bigint],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "setGuardrailMultiplier"
    ): TypedContractMethod<
        [_guardrailMultiplier: BigNumberish],
        [void],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "setStrategy"
    ): TypedContractMethod<
        [_strategy: AddressLike, _status: boolean],
        [void],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "setYTokenAndAllowance"
    ): TypedContractMethod<[_yToken: AddressLike], [void], "nonpayable">;
    getFunction(
        nameOrSignature: "sendToStrategy"
    ): TypedContractMethod<
        [token: AddressLike, amount: BigNumberish, strategy: AddressLike],
        [void],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "strategyAddress"
    ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
    getFunction(
        nameOrSignature: "symbol"
    ): TypedContractMethod<[], [string], "view">;
    getFunction(
        nameOrSignature: "totalAssets"
    ): TypedContractMethod<[], [bigint], "view">;
    getFunction(
        nameOrSignature: "totalSupply"
    ): TypedContractMethod<[], [bigint], "view">;
    getFunction(
        nameOrSignature: "transfer"
    ): TypedContractMethod<
        [to: AddressLike, value: BigNumberish],
        [boolean],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "transferFrom"
    ): TypedContractMethod<
        [from: AddressLike, to: AddressLike, value: BigNumberish],
        [boolean],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "withdraw"
    ): TypedContractMethod<
        [assets: BigNumberish, receiver: AddressLike, owner: AddressLike],
        [bigint],
        "nonpayable"
    >;
    getFunction(
        nameOrSignature: "yToken"
    ): TypedContractMethod<[], [string], "view">;

    filters: {};
}

