/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface YTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "approve"
      | "asset"
      | "balanceOf"
      | "convertToAssets"
      | "convertToShares"
      | "decimals"
      | "deposit"
      | "exchangeRate"
      | "exchangeRateScaled"
      | "manager"
      | "maxDeposit"
      | "maxMint"
      | "maxRedeem"
      | "maxWithdraw"
      | "mint"
      | "name"
      | "previewDeposit"
      | "previewMint"
      | "previewRedeem"
      | "previewWithdraw"
      | "redeem"
      | "symbol"
      | "totAssets"
      | "totalAssets"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "Deposit(address,address,uint256,uint256)"
      | "Deposit(address,address,address,uint256,uint256,uint256)"
      | "Transfer"
      | "Withdraw",
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "administrator",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "burnYToken",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "convertToAssets",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "convertToShares",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "exchangeRate",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "exchangeRateScaled",
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(functionFragment: "gasFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getUnvestedAmount",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [
      string,
      string,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "lastDistributionTimestamp",
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxDeposit",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "maxMint",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "maxRedeem",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "maxWithdraw",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "mintYToken",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewDeposit",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "previewMint",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "previewRedeem",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "previewWithdraw",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish, AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "rescue",
    values: [AddressLike, AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setAdministrator",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setGasFee",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setManager",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "setVestingPeriod",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setYield",
    values: [AddressLike],
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "totAssets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "transferInRewards",
    values: [BigNumberish, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: "updateTotalAssets",
    values: [BigNumberish, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: "vestingAmount",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "vestingPeriod",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, AddressLike, AddressLike],
  ): string;
  encodeFunctionData(functionFragment: "yield", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "administrator",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnYToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertToAssets",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToShares",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exchangeRate",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchangeRateScaled",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gasFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUnvestedAmount",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastDistributionTimestamp",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxMint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxRedeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxWithdraw",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintYToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewDeposit",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewMint",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewRedeem",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewWithdraw",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rescue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAdministrator",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGasFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVestingPeriod",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "setYield", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totAssets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferInRewards",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTotalAssets",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingAmount",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingPeriod",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yield", data: BytesLike): Result;
}

export namespace AdministratorSetEvent {
  export type InputTuple = [caller: AddressLike, newAdministrator: AddressLike];
  export type OutputTuple = [caller: string, newAdministrator: string];
  export interface OutputObject {
    caller: string;
    newAdministrator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish,
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Deposit_address_address_uint256_uint256_Event {
  export type InputTuple = [
    sender: AddressLike,
    owner: AddressLike,
    assets: BigNumberish,
    shares: BigNumberish,
  ];
  export type OutputTuple = [
    sender: string,
    owner: string,
    assets: bigint,
    shares: bigint,
  ];
  export interface OutputObject {
    sender: string;
    owner: string;
    assets: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Deposit_address_address_address_uint256_uint256_uint256_Event {
  export type InputTuple = [
    caller: AddressLike,
    receiver: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    sAmount: BigNumberish,
    shares: BigNumberish,
  ];
  export type OutputTuple = [
    caller: string,
    receiver: string,
    token: string,
    amount: bigint,
    sAmount: bigint,
    shares: bigint,
  ];
  export interface OutputObject {
    caller: string;
    receiver: string;
    token: string;
    amount: bigint;
    sAmount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeSetEvent {
  export type InputTuple = [caller: AddressLike, fee: BigNumberish];
  export type OutputTuple = [caller: string, fee: bigint];
  export interface OutputObject {
    caller: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasFeeSetEvent {
  export type InputTuple = [caller: AddressLike, gasFee: BigNumberish];
  export type OutputTuple = [caller: string, gasFee: bigint];
  export interface OutputObject {
    caller: string;
    gasFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerSetEvent {
  export type InputTuple = [caller: AddressLike, manager: AddressLike];
  export type OutputTuple = [caller: string, manager: string];
  export interface OutputObject {
    caller: string;
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RescueEvent {
  export type InputTuple = [
    caller: AddressLike,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
  ];
  export type OutputTuple = [
    caller: string,
    token: string,
    to: string,
    amount: bigint,
  ];
  export interface OutputObject {
    caller: string;
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TotalAssetsUpdatedEvent {
  export type InputTuple = [
    caller: AddressLike,
    amount: BigNumberish,
    add: boolean,
  ];
  export type OutputTuple = [caller: string, amount: bigint, add: boolean];
  export interface OutputObject {
    caller: string;
    amount: bigint;
    add: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish,
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRewardsEvent {
  export type InputTuple = [caller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [caller: string, amount: bigint];
  export interface OutputObject {
    caller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingPeriodSetEvent {
  export type InputTuple = [caller: AddressLike, vestingPeriod: BigNumberish];
  export type OutputTuple = [caller: string, vestingPeriod: bigint];
  export interface OutputObject {
    caller: string;
    vestingPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [
    sender: AddressLike,
    receiver: AddressLike,
    owner: AddressLike,
    assets: BigNumberish,
    shares: BigNumberish,
  ];
  export type OutputTuple = [
    sender: string,
    receiver: string,
    owner: string,
    assets: bigint,
    shares: bigint,
  ];
  export interface OutputObject {
    sender: string;
    receiver: string;
    owner: string;
    assets: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldSetEvent {
  export type InputTuple = [caller: AddressLike, yield_: AddressLike];
  export type OutputTuple = [caller: string, yield_: string];
  export interface OutputObject {
    caller: string;
    yield: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YToken extends BaseContract {
  connect(runner?: ContractRunner | null): YToken;
  waitForDeployment(): Promise<this>;

  interface: YTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  administrator: TypedContractMethod<[], [string], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  asset: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  burnYToken: TypedContractMethod<
    [from: AddressLike, shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  convertToAssets: TypedContractMethod<
    [shares: BigNumberish],
    [bigint],
    "view"
  >;

  convertToShares: TypedContractMethod<
    [assets: BigNumberish],
    [bigint],
    "view"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [assets: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;

  exchangeRate: TypedContractMethod<[], [bigint], "view">;

  exchangeRateScaled: TypedContractMethod<[], [bigint], "view">;

  fee: TypedContractMethod<[], [bigint], "view">;

  gasFee: TypedContractMethod<[], [bigint], "view">;

  getUnvestedAmount: TypedContractMethod<[], [bigint], "view">;

  init: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _asset: AddressLike,
      _yield: AddressLike,
      _manager: AddressLike,
      _administrator: AddressLike,
    ],
    [void],
    "nonpayable"
  >;

  lastDistributionTimestamp: TypedContractMethod<[], [bigint], "view">;

  manager: TypedContractMethod<[], [string], "view">;

  maxDeposit: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxMint: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxRedeem: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  maxWithdraw: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  mint: TypedContractMethod<
    [shares: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;

  mintYToken: TypedContractMethod<
    [to: AddressLike, shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  previewDeposit: TypedContractMethod<[assets: BigNumberish], [bigint], "view">;

  previewMint: TypedContractMethod<[shares: BigNumberish], [bigint], "view">;

  previewRedeem: TypedContractMethod<[shares: BigNumberish], [bigint], "view">;

  previewWithdraw: TypedContractMethod<
    [assets: BigNumberish],
    [bigint],
    "view"
  >;

  redeem: TypedContractMethod<
    [shares: BigNumberish, receiver: AddressLike, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  rescue: TypedContractMethod<
    [_token: AddressLike, _user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAdministrator: TypedContractMethod<
    [_administrator: AddressLike],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  setGasFee: TypedContractMethod<[_gasFee: BigNumberish], [void], "nonpayable">;

  setManager: TypedContractMethod<
    [_manager: AddressLike],
    [void],
    "nonpayable"
  >;

  setVestingPeriod: TypedContractMethod<
    [_vestingPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setYield: TypedContractMethod<[_yield: AddressLike], [void], "nonpayable">;

  symbol: TypedContractMethod<[], [string], "view">;

  totAssets: TypedContractMethod<[], [bigint], "view">;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferInRewards: TypedContractMethod<
    [amount: BigNumberish, profit: boolean],
    [void],
    "nonpayable"
  >;

  updateTotalAssets: TypedContractMethod<
    [_amount: BigNumberish, _add: boolean],
    [void],
    "nonpayable"
  >;

  vestingAmount: TypedContractMethod<[], [bigint], "view">;

  vestingPeriod: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<
    [assets: BigNumberish, receiver: AddressLike, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  yield: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "administrator",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowance",
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve",
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "asset",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf",
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burnYToken",
  ): TypedContractMethod<
    [from: AddressLike, shares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "convertToAssets",
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertToShares",
  ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit",
  ): TypedContractMethod<
    [assets: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exchangeRate",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "exchangeRateScaled",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fee",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gasFee",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUnvestedAmount",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "init",
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _asset: AddressLike,
      _yield: AddressLike,
      _manager: AddressLike,
      _administrator: AddressLike,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastDistributionTimestamp",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manager",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxDeposit",
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxMint",
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxRedeem",
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxWithdraw",
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint",
  ): TypedContractMethod<
    [shares: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintYToken",
  ): TypedContractMethod<
    [to: AddressLike, shares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewDeposit",
  ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewMint",
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewRedeem",
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewWithdraw",
  ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "redeem",
  ): TypedContractMethod<
    [shares: BigNumberish, receiver: AddressLike, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescue",
  ): TypedContractMethod<
    [_token: AddressLike, _user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdministrator",
  ): TypedContractMethod<[_administrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee",
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasFee",
  ): TypedContractMethod<[_gasFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setManager",
  ): TypedContractMethod<[_manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVestingPeriod",
  ): TypedContractMethod<[_vestingPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setYield",
  ): TypedContractMethod<[_yield: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totAssets",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalAssets",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer",
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom",
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferInRewards",
  ): TypedContractMethod<
    [amount: BigNumberish, profit: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTotalAssets",
  ): TypedContractMethod<
    [_amount: BigNumberish, _add: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vestingAmount",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vestingPeriod",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw",
  ): TypedContractMethod<
    [assets: BigNumberish, receiver: AddressLike, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "yield",
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AdministratorSet",
  ): TypedContractEvent<
    AdministratorSetEvent.InputTuple,
    AdministratorSetEvent.OutputTuple,
    AdministratorSetEvent.OutputObject
  >;
  getEvent(
    key: "Approval",
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "Deposit(address,address,uint256,uint256)",
  ): TypedContractEvent<
    Deposit_address_address_uint256_uint256_Event.InputTuple,
    Deposit_address_address_uint256_uint256_Event.OutputTuple,
    Deposit_address_address_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "Deposit(address,address,address,uint256,uint256,uint256)",
  ): TypedContractEvent<
    Deposit_address_address_address_uint256_uint256_uint256_Event.InputTuple,
    Deposit_address_address_address_uint256_uint256_uint256_Event.OutputTuple,
    Deposit_address_address_address_uint256_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "FeeSet",
  ): TypedContractEvent<
    FeeSetEvent.InputTuple,
    FeeSetEvent.OutputTuple,
    FeeSetEvent.OutputObject
  >;
  getEvent(
    key: "GasFeeSet",
  ): TypedContractEvent<
    GasFeeSetEvent.InputTuple,
    GasFeeSetEvent.OutputTuple,
    GasFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized",
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerSet",
  ): TypedContractEvent<
    ManagerSetEvent.InputTuple,
    ManagerSetEvent.OutputTuple,
    ManagerSetEvent.OutputObject
  >;
  getEvent(
    key: "Rescue",
  ): TypedContractEvent<
    RescueEvent.InputTuple,
    RescueEvent.OutputTuple,
    RescueEvent.OutputObject
  >;
  getEvent(
    key: "TotalAssetsUpdated",
  ): TypedContractEvent<
    TotalAssetsUpdatedEvent.InputTuple,
    TotalAssetsUpdatedEvent.OutputTuple,
    TotalAssetsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer",
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "TransferRewards",
  ): TypedContractEvent<
    TransferRewardsEvent.InputTuple,
    TransferRewardsEvent.OutputTuple,
    TransferRewardsEvent.OutputObject
  >;
  getEvent(
    key: "VestingPeriodSet",
  ): TypedContractEvent<
    VestingPeriodSetEvent.InputTuple,
    VestingPeriodSetEvent.OutputTuple,
    VestingPeriodSetEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw",
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;
  getEvent(
    key: "YieldSet",
  ): TypedContractEvent<
    YieldSetEvent.InputTuple,
    YieldSetEvent.OutputTuple,
    YieldSetEvent.OutputObject
  >;

  filters: {
    "AdministratorSet(address,address)": TypedContractEvent<
      AdministratorSetEvent.InputTuple,
      AdministratorSetEvent.OutputTuple,
      AdministratorSetEvent.OutputObject
    >;
    AdministratorSet: TypedContractEvent<
      AdministratorSetEvent.InputTuple,
      AdministratorSetEvent.OutputTuple,
      AdministratorSetEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "Deposit(address,address,uint256,uint256)": TypedContractEvent<
      Deposit_address_address_uint256_uint256_Event.InputTuple,
      Deposit_address_address_uint256_uint256_Event.OutputTuple,
      Deposit_address_address_uint256_uint256_Event.OutputObject
    >;
    "Deposit(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      Deposit_address_address_address_uint256_uint256_uint256_Event.InputTuple,
      Deposit_address_address_address_uint256_uint256_uint256_Event.OutputTuple,
      Deposit_address_address_address_uint256_uint256_uint256_Event.OutputObject
    >;

    "FeeSet(address,uint256)": TypedContractEvent<
      FeeSetEvent.InputTuple,
      FeeSetEvent.OutputTuple,
      FeeSetEvent.OutputObject
    >;
    FeeSet: TypedContractEvent<
      FeeSetEvent.InputTuple,
      FeeSetEvent.OutputTuple,
      FeeSetEvent.OutputObject
    >;

    "GasFeeSet(address,uint256)": TypedContractEvent<
      GasFeeSetEvent.InputTuple,
      GasFeeSetEvent.OutputTuple,
      GasFeeSetEvent.OutputObject
    >;
    GasFeeSet: TypedContractEvent<
      GasFeeSetEvent.InputTuple,
      GasFeeSetEvent.OutputTuple,
      GasFeeSetEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "ManagerSet(address,address)": TypedContractEvent<
      ManagerSetEvent.InputTuple,
      ManagerSetEvent.OutputTuple,
      ManagerSetEvent.OutputObject
    >;
    ManagerSet: TypedContractEvent<
      ManagerSetEvent.InputTuple,
      ManagerSetEvent.OutputTuple,
      ManagerSetEvent.OutputObject
    >;

    "Rescue(address,address,address,uint256)": TypedContractEvent<
      RescueEvent.InputTuple,
      RescueEvent.OutputTuple,
      RescueEvent.OutputObject
    >;
    Rescue: TypedContractEvent<
      RescueEvent.InputTuple,
      RescueEvent.OutputTuple,
      RescueEvent.OutputObject
    >;

    "TotalAssetsUpdated(address,uint256,bool)": TypedContractEvent<
      TotalAssetsUpdatedEvent.InputTuple,
      TotalAssetsUpdatedEvent.OutputTuple,
      TotalAssetsUpdatedEvent.OutputObject
    >;
    TotalAssetsUpdated: TypedContractEvent<
      TotalAssetsUpdatedEvent.InputTuple,
      TotalAssetsUpdatedEvent.OutputTuple,
      TotalAssetsUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "TransferRewards(address,uint256)": TypedContractEvent<
      TransferRewardsEvent.InputTuple,
      TransferRewardsEvent.OutputTuple,
      TransferRewardsEvent.OutputObject
    >;
    TransferRewards: TypedContractEvent<
      TransferRewardsEvent.InputTuple,
      TransferRewardsEvent.OutputTuple,
      TransferRewardsEvent.OutputObject
    >;

    "VestingPeriodSet(address,uint256)": TypedContractEvent<
      VestingPeriodSetEvent.InputTuple,
      VestingPeriodSetEvent.OutputTuple,
      VestingPeriodSetEvent.OutputObject
    >;
    VestingPeriodSet: TypedContractEvent<
      VestingPeriodSetEvent.InputTuple,
      VestingPeriodSetEvent.OutputTuple,
      VestingPeriodSetEvent.OutputObject
    >;

    "Withdraw(address,address,address,uint256,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;

    "YieldSet(address,address)": TypedContractEvent<
      YieldSetEvent.InputTuple,
      YieldSetEvent.OutputTuple,
      YieldSetEvent.OutputObject
    >;
    YieldSet: TypedContractEvent<
      YieldSetEvent.InputTuple,
      YieldSetEvent.OutputTuple,
      YieldSetEvent.OutputObject
    >;
  };
}
