/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Manager as ManagerV3 } from "./Manager";
export type { Vault as VaultContract } from "./Vault";

/**
 * YieldFi Contract TypeChain Types - V3 Contracts
 *
 * These are TypeScript types for YieldFi v3 smart contracts.
 */

// Export Manager v3 contract types with interface
export type { ManagerInterface as ManagerV3Interface } from "./Manager";

// Export Vault v3 contract types with interface
// Note: Exported as VaultContract to avoid conflict with Vault API type from ./types
export type { VaultInterface } from "./Vault";
