/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Manager {
  export type RedemptionQueueEntryStruct = {
    owner: AddressLike;
    receiver: AddressLike;
    lockedShares: BigNumberish;
    navAtRequest: BigNumberish;
    timestamp: BigNumberish;
  };

  export type RedemptionQueueEntryStructOutput = [
    owner: string,
    receiver: string,
    lockedShares: bigint,
    navAtRequest: bigint,
    timestamp: bigint
  ] & {
    owner: string;
    receiver: string;
    lockedShares: bigint;
    navAtRequest: bigint;
    timestamp: bigint;
  };
}

export interface ManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptTreasury"
      | "administrator"
      | "cancelRedemption"
      | "contracts"
      | "convertVaultAssetsToShares"
      | "convertVaultSharesToAssets"
      | "deposit"
      | "disableAsset"
      | "getNAV"
      | "getRedemptionQueueEntry"
      | "getRedemptionQueueLength"
      | "getStandardDebt"
      | "getVaultAsset"
      | "initialize"
      | "isBlacklisted"
      | "isVault"
      | "isVaultPaused"
      | "isWhitelisted"
      | "maxNavChangePercent"
      | "nextQueueIndex"
      | "paused"
      | "pendingTreasury"
      | "processRedemption"
      | "redemptionQueues"
      | "requestRedemption"
      | "rescueTokens"
      | "setAdministrator"
      | "setAssetWhitelist"
      | "setContracts"
      | "setMaxNavChangePercent"
      | "setPriceOracle"
      | "setTreasury"
      | "standardDebt"
      | "totalAssets"
      | "treasury"
      | "updateNav"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdministratorSet"
      | "AssetFeeConfigUpdated"
      | "AssetWhitelisted"
      | "BaseAssetUpdated"
      | "ContractsSet"
      | "CuratorUpdated"
      | "Deposit"
      | "DepositRecipientPending"
      | "DepositRecipientUpdated"
      | "FeatureDisabled"
      | "FeatureEnabled"
      | "FeatureInitialized"
      | "FeeReceiverPending"
      | "FeeReceiverUpdated"
      | "FeeTransferred"
      | "FeesClawedBack"
      | "Initialized"
      | "MaxNavChangePercentUpdated"
      | "NAVUpdated"
      | "NameAndSymbolUpdated"
      | "PriceOracleSet"
      | "RedemptionCancelled"
      | "RedemptionEnabled"
      | "RedemptionProcessed"
      | "RedemptionRequested"
      | "RedemptionSourceUpdated"
      | "SharesLocked"
      | "SharesUnlocked"
      | "TokensRescued"
      | "TransactionFeeStored"
      | "TransactionFeesWithdrawn"
      | "TreasuryPending"
      | "TreasuryUpdated"
      | "VaultFeesConfigured"
      | "VaultPaused"
      | "VaultRegistered"
      | "VaultUnpaused"
      | "VaultUnregistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "administrator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRedemption",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "contracts", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "convertVaultAssetsToShares",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertVaultSharesToAssets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disableAsset",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getNAV", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getRedemptionQueueEntry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRedemptionQueueLength",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStandardDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVaultPaused",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxNavChangePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextQueueIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processRedemption",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionQueues",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRedemption",
    values: [AddressLike, BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueTokens",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdministrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetWhitelist",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setContracts",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxNavChangePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "standardDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateNav",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "administrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contracts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertVaultAssetsToShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertVaultSharesToAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNAV", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRedemptionQueueEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedemptionQueueLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStandardDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVaultPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxNavChangePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextQueueIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionQueues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAdministrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxNavChangePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "standardDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateNav", data: BytesLike): Result;
}

export namespace AdministratorSetEvent {
  export type InputTuple = [caller: AddressLike, newAdministrator: AddressLike];
  export type OutputTuple = [caller: string, newAdministrator: string];
  export interface OutputObject {
    caller: string;
    newAdministrator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetFeeConfigUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    asset: AddressLike,
    depositFee: BigNumberish,
    redemptionFee: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    asset: string,
    depositFee: bigint,
    redemptionFee: bigint
  ];
  export interface OutputObject {
    vault: string;
    asset: string;
    depositFee: bigint;
    redemptionFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetWhitelistedEvent {
  export type InputTuple = [
    vault: AddressLike,
    asset: AddressLike,
    status: boolean
  ];
  export type OutputTuple = [vault: string, asset: string, status: boolean];
  export interface OutputObject {
    vault: string;
    asset: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseAssetUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldBaseAsset: AddressLike,
    newBaseAsset: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldBaseAsset: string,
    newBaseAsset: string
  ];
  export interface OutputObject {
    vault: string;
    oldBaseAsset: string;
    newBaseAsset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractsSetEvent {
  export type InputTuple = [
    registry: AddressLike,
    featureRegistry: AddressLike,
    navContract: AddressLike,
    priceOracle: AddressLike
  ];
  export type OutputTuple = [
    registry: string,
    featureRegistry: string,
    navContract: string,
    priceOracle: string
  ];
  export interface OutputObject {
    registry: string;
    featureRegistry: string;
    navContract: string;
    priceOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CuratorUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldCurator: AddressLike,
    newCurator: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldCurator: string,
    newCurator: string
  ];
  export interface OutputObject {
    vault: string;
    oldCurator: string;
    newCurator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    vault: AddressLike,
    asset: AddressLike,
    sender: AddressLike,
    receiver: AddressLike,
    assets: BigNumberish,
    shares: BigNumberish,
    feeShares: BigNumberish,
    referralCode: BytesLike
  ];
  export type OutputTuple = [
    vault: string,
    asset: string,
    sender: string,
    receiver: string,
    assets: bigint,
    shares: bigint,
    feeShares: bigint,
    referralCode: string
  ];
  export interface OutputObject {
    vault: string;
    asset: string;
    sender: string;
    receiver: string;
    assets: bigint;
    shares: bigint;
    feeShares: bigint;
    referralCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRecipientPendingEvent {
  export type InputTuple = [
    vault: AddressLike,
    pendingDepositRecipient: AddressLike
  ];
  export type OutputTuple = [vault: string, pendingDepositRecipient: string];
  export interface OutputObject {
    vault: string;
    pendingDepositRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRecipientUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldDepositRecipient: AddressLike,
    newDepositRecipient: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldDepositRecipient: string,
    newDepositRecipient: string
  ];
  export interface OutputObject {
    vault: string;
    oldDepositRecipient: string;
    newDepositRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeatureDisabledEvent {
  export type InputTuple = [vault: AddressLike, featureId: BytesLike];
  export type OutputTuple = [vault: string, featureId: string];
  export interface OutputObject {
    vault: string;
    featureId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeatureEnabledEvent {
  export type InputTuple = [vault: AddressLike, featureId: BytesLike];
  export type OutputTuple = [vault: string, featureId: string];
  export interface OutputObject {
    vault: string;
    featureId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeatureInitializedEvent {
  export type InputTuple = [vault: AddressLike, featureId: BytesLike];
  export type OutputTuple = [vault: string, featureId: string];
  export interface OutputObject {
    vault: string;
    featureId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceiverPendingEvent {
  export type InputTuple = [
    vault: AddressLike,
    pendingFeeReceiver: AddressLike
  ];
  export type OutputTuple = [vault: string, pendingFeeReceiver: string];
  export interface OutputObject {
    vault: string;
    pendingFeeReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceiverUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldFeeReceiver: AddressLike,
    newFeeReceiver: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldFeeReceiver: string,
    newFeeReceiver: string
  ];
  export interface OutputObject {
    vault: string;
    oldFeeReceiver: string;
    newFeeReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeTransferredEvent {
  export type InputTuple = [
    vault: AddressLike,
    feeReceiver: AddressLike,
    feeShares: BigNumberish,
    feeType: BigNumberish,
    asset: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    feeReceiver: string,
    feeShares: bigint,
    feeType: bigint,
    asset: string
  ];
  export interface OutputObject {
    vault: string;
    feeReceiver: string;
    feeShares: bigint;
    feeType: bigint;
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesClawedBackEvent {
  export type InputTuple = [
    vault: AddressLike,
    feeType: BigNumberish,
    treasury: AddressLike,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    feeType: bigint,
    treasury: string,
    shares: bigint
  ];
  export interface OutputObject {
    vault: string;
    feeType: bigint;
    treasury: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxNavChangePercentUpdatedEvent {
  export type InputTuple = [maxNavChangePercent: BigNumberish];
  export type OutputTuple = [maxNavChangePercent: bigint];
  export interface OutputObject {
    maxNavChangePercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NAVUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    newNav: BigNumberish,
    vestingEndTime: BigNumberish,
    managementFee: BigNumberish,
    performanceFee: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    newNav: bigint,
    vestingEndTime: bigint,
    managementFee: bigint,
    performanceFee: bigint
  ];
  export interface OutputObject {
    vault: string;
    newNav: bigint;
    vestingEndTime: bigint;
    managementFee: bigint;
    performanceFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameAndSymbolUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldName: string,
    oldSymbol: string,
    newName: string,
    newSymbol: string
  ];
  export type OutputTuple = [
    vault: string,
    oldName: string,
    oldSymbol: string,
    newName: string,
    newSymbol: string
  ];
  export interface OutputObject {
    vault: string;
    oldName: string;
    oldSymbol: string;
    newName: string;
    newSymbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceOracleSetEvent {
  export type InputTuple = [priceOracle: AddressLike];
  export type OutputTuple = [priceOracle: string];
  export interface OutputObject {
    priceOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionCancelledEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    queueIndex: BigNumberish
  ];
  export type OutputTuple = [vault: string, user: string, queueIndex: bigint];
  export interface OutputObject {
    vault: string;
    user: string;
    queueIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionEnabledEvent {
  export type InputTuple = [vault: AddressLike, enabled: boolean];
  export type OutputTuple = [vault: string, enabled: boolean];
  export interface OutputObject {
    vault: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionProcessedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    receiver: AddressLike,
    queueIndex: BigNumberish,
    assets: BigNumberish,
    effectiveNav: BigNumberish,
    burnShares: BigNumberish,
    gasFeeShares: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    user: string,
    receiver: string,
    queueIndex: bigint,
    assets: bigint,
    effectiveNav: bigint,
    burnShares: bigint,
    gasFeeShares: bigint
  ];
  export interface OutputObject {
    vault: string;
    user: string;
    receiver: string;
    queueIndex: bigint;
    assets: bigint;
    effectiveNav: bigint;
    burnShares: bigint;
    gasFeeShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionRequestedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    queueIndex: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    user: string,
    queueIndex: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    vault: string;
    user: string;
    queueIndex: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionSourceUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldRedemptionSource: AddressLike,
    newRedemptionSource: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldRedemptionSource: string,
    newRedemptionSource: string
  ];
  export interface OutputObject {
    vault: string;
    oldRedemptionSource: string;
    newRedemptionSource: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesLockedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [vault: string, user: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesUnlockedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [vault: string, user: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensRescuedEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionFeeStoredEvent {
  export type InputTuple = [
    vault: AddressLike,
    shares: BigNumberish,
    totalStored: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    shares: bigint,
    totalStored: bigint
  ];
  export interface OutputObject {
    vault: string;
    shares: bigint;
    totalStored: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionFeesWithdrawnEvent {
  export type InputTuple = [
    vault: AddressLike,
    recipient: AddressLike,
    transactionFeeShares: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    recipient: string,
    transactionFeeShares: bigint
  ];
  export interface OutputObject {
    vault: string;
    recipient: string;
    transactionFeeShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryPendingEvent {
  export type InputTuple = [pendingTreasury: AddressLike];
  export type OutputTuple = [pendingTreasury: string];
  export interface OutputObject {
    pendingTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultFeesConfiguredEvent {
  export type InputTuple = [
    vault: AddressLike,
    managementFee: BigNumberish,
    performanceFee: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    managementFee: bigint,
    performanceFee: bigint
  ];
  export interface OutputObject {
    vault: string;
    managementFee: bigint;
    performanceFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultPausedEvent {
  export type InputTuple = [vault: AddressLike, curator: AddressLike];
  export type OutputTuple = [vault: string, curator: string];
  export interface OutputObject {
    vault: string;
    curator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultRegisteredEvent {
  export type InputTuple = [
    vault: AddressLike,
    depositRecipient: AddressLike,
    redemptionSource: AddressLike,
    feeReceiver: AddressLike,
    curator: AddressLike,
    baseAsset: AddressLike,
    managementFee: BigNumberish,
    performanceFee: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    depositRecipient: string,
    redemptionSource: string,
    feeReceiver: string,
    curator: string,
    baseAsset: string,
    managementFee: bigint,
    performanceFee: bigint
  ];
  export interface OutputObject {
    vault: string;
    depositRecipient: string;
    redemptionSource: string;
    feeReceiver: string;
    curator: string;
    baseAsset: string;
    managementFee: bigint;
    performanceFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUnpausedEvent {
  export type InputTuple = [vault: AddressLike, operator: AddressLike];
  export type OutputTuple = [vault: string, operator: string];
  export interface OutputObject {
    vault: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUnregisteredEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Manager extends BaseContract {
  connect(runner?: ContractRunner | null): Manager;
  waitForDeployment(): Promise<this>;

  interface: ManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptTreasury: TypedContractMethod<[], [void], "nonpayable">;

  administrator: TypedContractMethod<[], [string], "view">;

  cancelRedemption: TypedContractMethod<
    [vault: AddressLike, queueIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  contracts: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        registry: string;
        featureRegistry: string;
        navContract: string;
        priceOracle: string;
      }
    ],
    "view"
  >;

  convertVaultAssetsToShares: TypedContractMethod<
    [vault: AddressLike, assets: BigNumberish],
    [bigint],
    "view"
  >;

  convertVaultSharesToAssets: TypedContractMethod<
    [vault: AddressLike, shares: BigNumberish],
    [bigint],
    "view"
  >;

  deposit: TypedContractMethod<
    [
      vault: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      receiver: AddressLike,
      minShares: BigNumberish,
      referralCode: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  disableAsset: TypedContractMethod<
    [vault: AddressLike, asset: AddressLike],
    [void],
    "nonpayable"
  >;

  getNAV: TypedContractMethod<[vault: AddressLike], [bigint], "view">;

  getRedemptionQueueEntry: TypedContractMethod<
    [vault: AddressLike, queueIndex: BigNumberish],
    [Manager.RedemptionQueueEntryStructOutput],
    "view"
  >;

  getRedemptionQueueLength: TypedContractMethod<
    [vault: AddressLike],
    [bigint],
    "view"
  >;

  getStandardDebt: TypedContractMethod<[vault: AddressLike], [bigint], "view">;

  getVaultAsset: TypedContractMethod<[vault: AddressLike], [string], "view">;

  initialize: TypedContractMethod<
    [
      administrator_: AddressLike,
      registry_: AddressLike,
      featureRegistry_: AddressLike,
      navContract_: AddressLike,
      priceOracle_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isBlacklisted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isVault: TypedContractMethod<[vault: AddressLike], [boolean], "view">;

  isVaultPaused: TypedContractMethod<[vault: AddressLike], [boolean], "view">;

  isWhitelisted: TypedContractMethod<
    [vault: AddressLike, asset: AddressLike],
    [boolean],
    "view"
  >;

  maxNavChangePercent: TypedContractMethod<[], [bigint], "view">;

  nextQueueIndex: TypedContractMethod<[vault: AddressLike], [bigint], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingTreasury: TypedContractMethod<[], [string], "view">;

  processRedemption: TypedContractMethod<
    [vault: AddressLike, queueIndex: BigNumberish, gasFeeShares: BigNumberish],
    [void],
    "nonpayable"
  >;

  redemptionQueues: TypedContractMethod<
    [vault: AddressLike, queueIndex: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        owner: string;
        receiver: string;
        lockedShares: bigint;
        navAtRequest: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  requestRedemption: TypedContractMethod<
    [
      vault: AddressLike,
      shares: BigNumberish,
      owner: AddressLike,
      receiver: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  rescueTokens: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAdministrator: TypedContractMethod<
    [_administrator: AddressLike],
    [void],
    "nonpayable"
  >;

  setAssetWhitelist: TypedContractMethod<
    [vault: AddressLike, asset: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setContracts: TypedContractMethod<
    [
      registry_: AddressLike,
      featureRegistry_: AddressLike,
      navContract_: AddressLike,
      priceOracle_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setMaxNavChangePercent: TypedContractMethod<
    [maxNavChangePercent_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPriceOracle: TypedContractMethod<
    [priceOracle_: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [treasury_: AddressLike],
    [void],
    "nonpayable"
  >;

  standardDebt: TypedContractMethod<[vault: AddressLike], [bigint], "view">;

  totalAssets: TypedContractMethod<[vault: AddressLike], [bigint], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  updateNav: TypedContractMethod<
    [
      vault: AddressLike,
      newNav: BigNumberish,
      vestingEndTime: BigNumberish,
      managementFee: BigNumberish,
      performanceFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptTreasury"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "administrator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelRedemption"
  ): TypedContractMethod<
    [vault: AddressLike, queueIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contracts"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        registry: string;
        featureRegistry: string;
        navContract: string;
        priceOracle: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "convertVaultAssetsToShares"
  ): TypedContractMethod<
    [vault: AddressLike, assets: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "convertVaultSharesToAssets"
  ): TypedContractMethod<
    [vault: AddressLike, shares: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      receiver: AddressLike,
      minShares: BigNumberish,
      referralCode: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disableAsset"
  ): TypedContractMethod<
    [vault: AddressLike, asset: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNAV"
  ): TypedContractMethod<[vault: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRedemptionQueueEntry"
  ): TypedContractMethod<
    [vault: AddressLike, queueIndex: BigNumberish],
    [Manager.RedemptionQueueEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRedemptionQueueLength"
  ): TypedContractMethod<[vault: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStandardDebt"
  ): TypedContractMethod<[vault: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultAsset"
  ): TypedContractMethod<[vault: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      administrator_: AddressLike,
      registry_: AddressLike,
      featureRegistry_: AddressLike,
      navContract_: AddressLike,
      priceOracle_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVault"
  ): TypedContractMethod<[vault: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVaultPaused"
  ): TypedContractMethod<[vault: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<
    [vault: AddressLike, asset: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxNavChangePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextQueueIndex"
  ): TypedContractMethod<[vault: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processRedemption"
  ): TypedContractMethod<
    [vault: AddressLike, queueIndex: BigNumberish, gasFeeShares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redemptionQueues"
  ): TypedContractMethod<
    [vault: AddressLike, queueIndex: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        owner: string;
        receiver: string;
        lockedShares: bigint;
        navAtRequest: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestRedemption"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      shares: BigNumberish,
      owner: AddressLike,
      receiver: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueTokens"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdministrator"
  ): TypedContractMethod<[_administrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAssetWhitelist"
  ): TypedContractMethod<
    [vault: AddressLike, asset: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setContracts"
  ): TypedContractMethod<
    [
      registry_: AddressLike,
      featureRegistry_: AddressLike,
      navContract_: AddressLike,
      priceOracle_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxNavChangePercent"
  ): TypedContractMethod<
    [maxNavChangePercent_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPriceOracle"
  ): TypedContractMethod<[priceOracle_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[treasury_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "standardDebt"
  ): TypedContractMethod<[vault: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[vault: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateNav"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      newNav: BigNumberish,
      vestingEndTime: BigNumberish,
      managementFee: BigNumberish,
      performanceFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdministratorSet"
  ): TypedContractEvent<
    AdministratorSetEvent.InputTuple,
    AdministratorSetEvent.OutputTuple,
    AdministratorSetEvent.OutputObject
  >;
  getEvent(
    key: "AssetFeeConfigUpdated"
  ): TypedContractEvent<
    AssetFeeConfigUpdatedEvent.InputTuple,
    AssetFeeConfigUpdatedEvent.OutputTuple,
    AssetFeeConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AssetWhitelisted"
  ): TypedContractEvent<
    AssetWhitelistedEvent.InputTuple,
    AssetWhitelistedEvent.OutputTuple,
    AssetWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "BaseAssetUpdated"
  ): TypedContractEvent<
    BaseAssetUpdatedEvent.InputTuple,
    BaseAssetUpdatedEvent.OutputTuple,
    BaseAssetUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractsSet"
  ): TypedContractEvent<
    ContractsSetEvent.InputTuple,
    ContractsSetEvent.OutputTuple,
    ContractsSetEvent.OutputObject
  >;
  getEvent(
    key: "CuratorUpdated"
  ): TypedContractEvent<
    CuratorUpdatedEvent.InputTuple,
    CuratorUpdatedEvent.OutputTuple,
    CuratorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "DepositRecipientPending"
  ): TypedContractEvent<
    DepositRecipientPendingEvent.InputTuple,
    DepositRecipientPendingEvent.OutputTuple,
    DepositRecipientPendingEvent.OutputObject
  >;
  getEvent(
    key: "DepositRecipientUpdated"
  ): TypedContractEvent<
    DepositRecipientUpdatedEvent.InputTuple,
    DepositRecipientUpdatedEvent.OutputTuple,
    DepositRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeatureDisabled"
  ): TypedContractEvent<
    FeatureDisabledEvent.InputTuple,
    FeatureDisabledEvent.OutputTuple,
    FeatureDisabledEvent.OutputObject
  >;
  getEvent(
    key: "FeatureEnabled"
  ): TypedContractEvent<
    FeatureEnabledEvent.InputTuple,
    FeatureEnabledEvent.OutputTuple,
    FeatureEnabledEvent.OutputObject
  >;
  getEvent(
    key: "FeatureInitialized"
  ): TypedContractEvent<
    FeatureInitializedEvent.InputTuple,
    FeatureInitializedEvent.OutputTuple,
    FeatureInitializedEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceiverPending"
  ): TypedContractEvent<
    FeeReceiverPendingEvent.InputTuple,
    FeeReceiverPendingEvent.OutputTuple,
    FeeReceiverPendingEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceiverUpdated"
  ): TypedContractEvent<
    FeeReceiverUpdatedEvent.InputTuple,
    FeeReceiverUpdatedEvent.OutputTuple,
    FeeReceiverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeTransferred"
  ): TypedContractEvent<
    FeeTransferredEvent.InputTuple,
    FeeTransferredEvent.OutputTuple,
    FeeTransferredEvent.OutputObject
  >;
  getEvent(
    key: "FeesClawedBack"
  ): TypedContractEvent<
    FeesClawedBackEvent.InputTuple,
    FeesClawedBackEvent.OutputTuple,
    FeesClawedBackEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MaxNavChangePercentUpdated"
  ): TypedContractEvent<
    MaxNavChangePercentUpdatedEvent.InputTuple,
    MaxNavChangePercentUpdatedEvent.OutputTuple,
    MaxNavChangePercentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NAVUpdated"
  ): TypedContractEvent<
    NAVUpdatedEvent.InputTuple,
    NAVUpdatedEvent.OutputTuple,
    NAVUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NameAndSymbolUpdated"
  ): TypedContractEvent<
    NameAndSymbolUpdatedEvent.InputTuple,
    NameAndSymbolUpdatedEvent.OutputTuple,
    NameAndSymbolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PriceOracleSet"
  ): TypedContractEvent<
    PriceOracleSetEvent.InputTuple,
    PriceOracleSetEvent.OutputTuple,
    PriceOracleSetEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionCancelled"
  ): TypedContractEvent<
    RedemptionCancelledEvent.InputTuple,
    RedemptionCancelledEvent.OutputTuple,
    RedemptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionEnabled"
  ): TypedContractEvent<
    RedemptionEnabledEvent.InputTuple,
    RedemptionEnabledEvent.OutputTuple,
    RedemptionEnabledEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionProcessed"
  ): TypedContractEvent<
    RedemptionProcessedEvent.InputTuple,
    RedemptionProcessedEvent.OutputTuple,
    RedemptionProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionRequested"
  ): TypedContractEvent<
    RedemptionRequestedEvent.InputTuple,
    RedemptionRequestedEvent.OutputTuple,
    RedemptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionSourceUpdated"
  ): TypedContractEvent<
    RedemptionSourceUpdatedEvent.InputTuple,
    RedemptionSourceUpdatedEvent.OutputTuple,
    RedemptionSourceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SharesLocked"
  ): TypedContractEvent<
    SharesLockedEvent.InputTuple,
    SharesLockedEvent.OutputTuple,
    SharesLockedEvent.OutputObject
  >;
  getEvent(
    key: "SharesUnlocked"
  ): TypedContractEvent<
    SharesUnlockedEvent.InputTuple,
    SharesUnlockedEvent.OutputTuple,
    SharesUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "TokensRescued"
  ): TypedContractEvent<
    TokensRescuedEvent.InputTuple,
    TokensRescuedEvent.OutputTuple,
    TokensRescuedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionFeeStored"
  ): TypedContractEvent<
    TransactionFeeStoredEvent.InputTuple,
    TransactionFeeStoredEvent.OutputTuple,
    TransactionFeeStoredEvent.OutputObject
  >;
  getEvent(
    key: "TransactionFeesWithdrawn"
  ): TypedContractEvent<
    TransactionFeesWithdrawnEvent.InputTuple,
    TransactionFeesWithdrawnEvent.OutputTuple,
    TransactionFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryPending"
  ): TypedContractEvent<
    TreasuryPendingEvent.InputTuple,
    TreasuryPendingEvent.OutputTuple,
    TreasuryPendingEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultFeesConfigured"
  ): TypedContractEvent<
    VaultFeesConfiguredEvent.InputTuple,
    VaultFeesConfiguredEvent.OutputTuple,
    VaultFeesConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "VaultPaused"
  ): TypedContractEvent<
    VaultPausedEvent.InputTuple,
    VaultPausedEvent.OutputTuple,
    VaultPausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultRegistered"
  ): TypedContractEvent<
    VaultRegisteredEvent.InputTuple,
    VaultRegisteredEvent.OutputTuple,
    VaultRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VaultUnpaused"
  ): TypedContractEvent<
    VaultUnpausedEvent.InputTuple,
    VaultUnpausedEvent.OutputTuple,
    VaultUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultUnregistered"
  ): TypedContractEvent<
    VaultUnregisteredEvent.InputTuple,
    VaultUnregisteredEvent.OutputTuple,
    VaultUnregisteredEvent.OutputObject
  >;

  filters: {
    "AdministratorSet(address,address)": TypedContractEvent<
      AdministratorSetEvent.InputTuple,
      AdministratorSetEvent.OutputTuple,
      AdministratorSetEvent.OutputObject
    >;
    AdministratorSet: TypedContractEvent<
      AdministratorSetEvent.InputTuple,
      AdministratorSetEvent.OutputTuple,
      AdministratorSetEvent.OutputObject
    >;

    "AssetFeeConfigUpdated(address,address,uint256,uint256)": TypedContractEvent<
      AssetFeeConfigUpdatedEvent.InputTuple,
      AssetFeeConfigUpdatedEvent.OutputTuple,
      AssetFeeConfigUpdatedEvent.OutputObject
    >;
    AssetFeeConfigUpdated: TypedContractEvent<
      AssetFeeConfigUpdatedEvent.InputTuple,
      AssetFeeConfigUpdatedEvent.OutputTuple,
      AssetFeeConfigUpdatedEvent.OutputObject
    >;

    "AssetWhitelisted(address,address,bool)": TypedContractEvent<
      AssetWhitelistedEvent.InputTuple,
      AssetWhitelistedEvent.OutputTuple,
      AssetWhitelistedEvent.OutputObject
    >;
    AssetWhitelisted: TypedContractEvent<
      AssetWhitelistedEvent.InputTuple,
      AssetWhitelistedEvent.OutputTuple,
      AssetWhitelistedEvent.OutputObject
    >;

    "BaseAssetUpdated(address,address,address)": TypedContractEvent<
      BaseAssetUpdatedEvent.InputTuple,
      BaseAssetUpdatedEvent.OutputTuple,
      BaseAssetUpdatedEvent.OutputObject
    >;
    BaseAssetUpdated: TypedContractEvent<
      BaseAssetUpdatedEvent.InputTuple,
      BaseAssetUpdatedEvent.OutputTuple,
      BaseAssetUpdatedEvent.OutputObject
    >;

    "ContractsSet(address,address,address,address)": TypedContractEvent<
      ContractsSetEvent.InputTuple,
      ContractsSetEvent.OutputTuple,
      ContractsSetEvent.OutputObject
    >;
    ContractsSet: TypedContractEvent<
      ContractsSetEvent.InputTuple,
      ContractsSetEvent.OutputTuple,
      ContractsSetEvent.OutputObject
    >;

    "CuratorUpdated(address,address,address)": TypedContractEvent<
      CuratorUpdatedEvent.InputTuple,
      CuratorUpdatedEvent.OutputTuple,
      CuratorUpdatedEvent.OutputObject
    >;
    CuratorUpdated: TypedContractEvent<
      CuratorUpdatedEvent.InputTuple,
      CuratorUpdatedEvent.OutputTuple,
      CuratorUpdatedEvent.OutputObject
    >;

    "Deposit(address,address,address,address,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "DepositRecipientPending(address,address)": TypedContractEvent<
      DepositRecipientPendingEvent.InputTuple,
      DepositRecipientPendingEvent.OutputTuple,
      DepositRecipientPendingEvent.OutputObject
    >;
    DepositRecipientPending: TypedContractEvent<
      DepositRecipientPendingEvent.InputTuple,
      DepositRecipientPendingEvent.OutputTuple,
      DepositRecipientPendingEvent.OutputObject
    >;

    "DepositRecipientUpdated(address,address,address)": TypedContractEvent<
      DepositRecipientUpdatedEvent.InputTuple,
      DepositRecipientUpdatedEvent.OutputTuple,
      DepositRecipientUpdatedEvent.OutputObject
    >;
    DepositRecipientUpdated: TypedContractEvent<
      DepositRecipientUpdatedEvent.InputTuple,
      DepositRecipientUpdatedEvent.OutputTuple,
      DepositRecipientUpdatedEvent.OutputObject
    >;

    "FeatureDisabled(address,bytes32)": TypedContractEvent<
      FeatureDisabledEvent.InputTuple,
      FeatureDisabledEvent.OutputTuple,
      FeatureDisabledEvent.OutputObject
    >;
    FeatureDisabled: TypedContractEvent<
      FeatureDisabledEvent.InputTuple,
      FeatureDisabledEvent.OutputTuple,
      FeatureDisabledEvent.OutputObject
    >;

    "FeatureEnabled(address,bytes32)": TypedContractEvent<
      FeatureEnabledEvent.InputTuple,
      FeatureEnabledEvent.OutputTuple,
      FeatureEnabledEvent.OutputObject
    >;
    FeatureEnabled: TypedContractEvent<
      FeatureEnabledEvent.InputTuple,
      FeatureEnabledEvent.OutputTuple,
      FeatureEnabledEvent.OutputObject
    >;

    "FeatureInitialized(address,bytes32)": TypedContractEvent<
      FeatureInitializedEvent.InputTuple,
      FeatureInitializedEvent.OutputTuple,
      FeatureInitializedEvent.OutputObject
    >;
    FeatureInitialized: TypedContractEvent<
      FeatureInitializedEvent.InputTuple,
      FeatureInitializedEvent.OutputTuple,
      FeatureInitializedEvent.OutputObject
    >;

    "FeeReceiverPending(address,address)": TypedContractEvent<
      FeeReceiverPendingEvent.InputTuple,
      FeeReceiverPendingEvent.OutputTuple,
      FeeReceiverPendingEvent.OutputObject
    >;
    FeeReceiverPending: TypedContractEvent<
      FeeReceiverPendingEvent.InputTuple,
      FeeReceiverPendingEvent.OutputTuple,
      FeeReceiverPendingEvent.OutputObject
    >;

    "FeeReceiverUpdated(address,address,address)": TypedContractEvent<
      FeeReceiverUpdatedEvent.InputTuple,
      FeeReceiverUpdatedEvent.OutputTuple,
      FeeReceiverUpdatedEvent.OutputObject
    >;
    FeeReceiverUpdated: TypedContractEvent<
      FeeReceiverUpdatedEvent.InputTuple,
      FeeReceiverUpdatedEvent.OutputTuple,
      FeeReceiverUpdatedEvent.OutputObject
    >;

    "FeeTransferred(address,address,uint256,uint8,address)": TypedContractEvent<
      FeeTransferredEvent.InputTuple,
      FeeTransferredEvent.OutputTuple,
      FeeTransferredEvent.OutputObject
    >;
    FeeTransferred: TypedContractEvent<
      FeeTransferredEvent.InputTuple,
      FeeTransferredEvent.OutputTuple,
      FeeTransferredEvent.OutputObject
    >;

    "FeesClawedBack(address,uint8,address,uint256)": TypedContractEvent<
      FeesClawedBackEvent.InputTuple,
      FeesClawedBackEvent.OutputTuple,
      FeesClawedBackEvent.OutputObject
    >;
    FeesClawedBack: TypedContractEvent<
      FeesClawedBackEvent.InputTuple,
      FeesClawedBackEvent.OutputTuple,
      FeesClawedBackEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MaxNavChangePercentUpdated(uint256)": TypedContractEvent<
      MaxNavChangePercentUpdatedEvent.InputTuple,
      MaxNavChangePercentUpdatedEvent.OutputTuple,
      MaxNavChangePercentUpdatedEvent.OutputObject
    >;
    MaxNavChangePercentUpdated: TypedContractEvent<
      MaxNavChangePercentUpdatedEvent.InputTuple,
      MaxNavChangePercentUpdatedEvent.OutputTuple,
      MaxNavChangePercentUpdatedEvent.OutputObject
    >;

    "NAVUpdated(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      NAVUpdatedEvent.InputTuple,
      NAVUpdatedEvent.OutputTuple,
      NAVUpdatedEvent.OutputObject
    >;
    NAVUpdated: TypedContractEvent<
      NAVUpdatedEvent.InputTuple,
      NAVUpdatedEvent.OutputTuple,
      NAVUpdatedEvent.OutputObject
    >;

    "NameAndSymbolUpdated(address,string,string,string,string)": TypedContractEvent<
      NameAndSymbolUpdatedEvent.InputTuple,
      NameAndSymbolUpdatedEvent.OutputTuple,
      NameAndSymbolUpdatedEvent.OutputObject
    >;
    NameAndSymbolUpdated: TypedContractEvent<
      NameAndSymbolUpdatedEvent.InputTuple,
      NameAndSymbolUpdatedEvent.OutputTuple,
      NameAndSymbolUpdatedEvent.OutputObject
    >;

    "PriceOracleSet(address)": TypedContractEvent<
      PriceOracleSetEvent.InputTuple,
      PriceOracleSetEvent.OutputTuple,
      PriceOracleSetEvent.OutputObject
    >;
    PriceOracleSet: TypedContractEvent<
      PriceOracleSetEvent.InputTuple,
      PriceOracleSetEvent.OutputTuple,
      PriceOracleSetEvent.OutputObject
    >;

    "RedemptionCancelled(address,address,uint256)": TypedContractEvent<
      RedemptionCancelledEvent.InputTuple,
      RedemptionCancelledEvent.OutputTuple,
      RedemptionCancelledEvent.OutputObject
    >;
    RedemptionCancelled: TypedContractEvent<
      RedemptionCancelledEvent.InputTuple,
      RedemptionCancelledEvent.OutputTuple,
      RedemptionCancelledEvent.OutputObject
    >;

    "RedemptionEnabled(address,bool)": TypedContractEvent<
      RedemptionEnabledEvent.InputTuple,
      RedemptionEnabledEvent.OutputTuple,
      RedemptionEnabledEvent.OutputObject
    >;
    RedemptionEnabled: TypedContractEvent<
      RedemptionEnabledEvent.InputTuple,
      RedemptionEnabledEvent.OutputTuple,
      RedemptionEnabledEvent.OutputObject
    >;

    "RedemptionProcessed(address,address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RedemptionProcessedEvent.InputTuple,
      RedemptionProcessedEvent.OutputTuple,
      RedemptionProcessedEvent.OutputObject
    >;
    RedemptionProcessed: TypedContractEvent<
      RedemptionProcessedEvent.InputTuple,
      RedemptionProcessedEvent.OutputTuple,
      RedemptionProcessedEvent.OutputObject
    >;

    "RedemptionRequested(address,address,uint256,uint256)": TypedContractEvent<
      RedemptionRequestedEvent.InputTuple,
      RedemptionRequestedEvent.OutputTuple,
      RedemptionRequestedEvent.OutputObject
    >;
    RedemptionRequested: TypedContractEvent<
      RedemptionRequestedEvent.InputTuple,
      RedemptionRequestedEvent.OutputTuple,
      RedemptionRequestedEvent.OutputObject
    >;

    "RedemptionSourceUpdated(address,address,address)": TypedContractEvent<
      RedemptionSourceUpdatedEvent.InputTuple,
      RedemptionSourceUpdatedEvent.OutputTuple,
      RedemptionSourceUpdatedEvent.OutputObject
    >;
    RedemptionSourceUpdated: TypedContractEvent<
      RedemptionSourceUpdatedEvent.InputTuple,
      RedemptionSourceUpdatedEvent.OutputTuple,
      RedemptionSourceUpdatedEvent.OutputObject
    >;

    "SharesLocked(address,address,uint256)": TypedContractEvent<
      SharesLockedEvent.InputTuple,
      SharesLockedEvent.OutputTuple,
      SharesLockedEvent.OutputObject
    >;
    SharesLocked: TypedContractEvent<
      SharesLockedEvent.InputTuple,
      SharesLockedEvent.OutputTuple,
      SharesLockedEvent.OutputObject
    >;

    "SharesUnlocked(address,address,uint256)": TypedContractEvent<
      SharesUnlockedEvent.InputTuple,
      SharesUnlockedEvent.OutputTuple,
      SharesUnlockedEvent.OutputObject
    >;
    SharesUnlocked: TypedContractEvent<
      SharesUnlockedEvent.InputTuple,
      SharesUnlockedEvent.OutputTuple,
      SharesUnlockedEvent.OutputObject
    >;

    "TokensRescued(address,address,uint256)": TypedContractEvent<
      TokensRescuedEvent.InputTuple,
      TokensRescuedEvent.OutputTuple,
      TokensRescuedEvent.OutputObject
    >;
    TokensRescued: TypedContractEvent<
      TokensRescuedEvent.InputTuple,
      TokensRescuedEvent.OutputTuple,
      TokensRescuedEvent.OutputObject
    >;

    "TransactionFeeStored(address,uint256,uint256)": TypedContractEvent<
      TransactionFeeStoredEvent.InputTuple,
      TransactionFeeStoredEvent.OutputTuple,
      TransactionFeeStoredEvent.OutputObject
    >;
    TransactionFeeStored: TypedContractEvent<
      TransactionFeeStoredEvent.InputTuple,
      TransactionFeeStoredEvent.OutputTuple,
      TransactionFeeStoredEvent.OutputObject
    >;

    "TransactionFeesWithdrawn(address,address,uint256)": TypedContractEvent<
      TransactionFeesWithdrawnEvent.InputTuple,
      TransactionFeesWithdrawnEvent.OutputTuple,
      TransactionFeesWithdrawnEvent.OutputObject
    >;
    TransactionFeesWithdrawn: TypedContractEvent<
      TransactionFeesWithdrawnEvent.InputTuple,
      TransactionFeesWithdrawnEvent.OutputTuple,
      TransactionFeesWithdrawnEvent.OutputObject
    >;

    "TreasuryPending(address)": TypedContractEvent<
      TreasuryPendingEvent.InputTuple,
      TreasuryPendingEvent.OutputTuple,
      TreasuryPendingEvent.OutputObject
    >;
    TreasuryPending: TypedContractEvent<
      TreasuryPendingEvent.InputTuple,
      TreasuryPendingEvent.OutputTuple,
      TreasuryPendingEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "VaultFeesConfigured(address,uint256,uint256)": TypedContractEvent<
      VaultFeesConfiguredEvent.InputTuple,
      VaultFeesConfiguredEvent.OutputTuple,
      VaultFeesConfiguredEvent.OutputObject
    >;
    VaultFeesConfigured: TypedContractEvent<
      VaultFeesConfiguredEvent.InputTuple,
      VaultFeesConfiguredEvent.OutputTuple,
      VaultFeesConfiguredEvent.OutputObject
    >;

    "VaultPaused(address,address)": TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;
    VaultPaused: TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;

    "VaultRegistered(address,address,address,address,address,address,uint256,uint256)": TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;
    VaultRegistered: TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;

    "VaultUnpaused(address,address)": TypedContractEvent<
      VaultUnpausedEvent.InputTuple,
      VaultUnpausedEvent.OutputTuple,
      VaultUnpausedEvent.OutputObject
    >;
    VaultUnpaused: TypedContractEvent<
      VaultUnpausedEvent.InputTuple,
      VaultUnpausedEvent.OutputTuple,
      VaultUnpausedEvent.OutputObject
    >;

    "VaultUnregistered(address)": TypedContractEvent<
      VaultUnregisteredEvent.InputTuple,
      VaultUnregisteredEvent.OutputTuple,
      VaultUnregisteredEvent.OutputObject
    >;
    VaultUnregistered: TypedContractEvent<
      VaultUnregisteredEvent.InputTuple,
      VaultUnregisteredEvent.OutputTuple,
      VaultUnregisteredEvent.OutputObject
    >;
  };
}
