/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "administrator"
      | "allowance"
      | "approve"
      | "approveManager"
      | "asset"
      | "balanceOf"
      | "burn"
      | "convertToAssets"
      | "convertToShares"
      | "decimals"
      | "deposit"
      | "getCCIPAdmin"
      | "getRate"
      | "initialize"
      | "isBlacklisted"
      | "latestRoundData"
      | "lockShares"
      | "lockedShares"
      | "manager"
      | "maxDeposit"
      | "maxRedeem"
      | "mint"
      | "name"
      | "paused"
      | "previewDeposit"
      | "previewMint"
      | "previewRedeem"
      | "previewWithdraw"
      | "rescueTokens"
      | "setAdministrator"
      | "setNameAndSymbol"
      | "spendAllowance"
      | "symbol"
      | "totalAssets"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "unlockShares"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdministratorSet"
      | "Approval"
      | "AssetFeeConfigUpdated"
      | "AssetWhitelisted"
      | "BaseAssetUpdated"
      | "ContractsSet"
      | "CuratorUpdated"
      | "Deposit"
      | "DepositRecipientPending"
      | "DepositRecipientUpdated"
      | "FeatureDisabled"
      | "FeatureEnabled"
      | "FeatureInitialized"
      | "FeeReceiverPending"
      | "FeeReceiverUpdated"
      | "FeeTransferred"
      | "FeesClawedBack"
      | "Initialized"
      | "MaxNavChangePercentUpdated"
      | "NAVUpdated"
      | "NameAndSymbolUpdated"
      | "PriceOracleSet"
      | "RedemptionCancelled"
      | "RedemptionEnabled"
      | "RedemptionProcessed"
      | "RedemptionRequested"
      | "RedemptionSourceUpdated"
      | "SharesLocked"
      | "SharesUnlocked"
      | "TokensRescued"
      | "TransactionFeeStored"
      | "TransactionFeesWithdrawn"
      | "Transfer"
      | "TreasuryPending"
      | "TreasuryUpdated"
      | "VaultFeesConfigured"
      | "VaultPaused"
      | "VaultRegistered"
      | "VaultUnpaused"
      | "VaultUnregistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "administrator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCCIPAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRoundData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockShares",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxDeposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRedeem",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewMint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewRedeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueTokens",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdministrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNameAndSymbol",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "spendAllowance",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockShares",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "administrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertToAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCCIPAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxRedeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAdministrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNameAndSymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockShares",
    data: BytesLike
  ): Result;
}

export namespace AdministratorSetEvent {
  export type InputTuple = [caller: AddressLike, newAdministrator: AddressLike];
  export type OutputTuple = [caller: string, newAdministrator: string];
  export interface OutputObject {
    caller: string;
    newAdministrator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetFeeConfigUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    asset: AddressLike,
    depositFee: BigNumberish,
    redemptionFee: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    asset: string,
    depositFee: bigint,
    redemptionFee: bigint
  ];
  export interface OutputObject {
    vault: string;
    asset: string;
    depositFee: bigint;
    redemptionFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetWhitelistedEvent {
  export type InputTuple = [
    vault: AddressLike,
    asset: AddressLike,
    status: boolean
  ];
  export type OutputTuple = [vault: string, asset: string, status: boolean];
  export interface OutputObject {
    vault: string;
    asset: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseAssetUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldBaseAsset: AddressLike,
    newBaseAsset: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldBaseAsset: string,
    newBaseAsset: string
  ];
  export interface OutputObject {
    vault: string;
    oldBaseAsset: string;
    newBaseAsset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractsSetEvent {
  export type InputTuple = [
    registry: AddressLike,
    featureRegistry: AddressLike,
    navContract: AddressLike,
    priceOracle: AddressLike
  ];
  export type OutputTuple = [
    registry: string,
    featureRegistry: string,
    navContract: string,
    priceOracle: string
  ];
  export interface OutputObject {
    registry: string;
    featureRegistry: string;
    navContract: string;
    priceOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CuratorUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldCurator: AddressLike,
    newCurator: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldCurator: string,
    newCurator: string
  ];
  export interface OutputObject {
    vault: string;
    oldCurator: string;
    newCurator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    vault: AddressLike,
    asset: AddressLike,
    sender: AddressLike,
    receiver: AddressLike,
    assets: BigNumberish,
    shares: BigNumberish,
    feeShares: BigNumberish,
    referralCode: BytesLike
  ];
  export type OutputTuple = [
    vault: string,
    asset: string,
    sender: string,
    receiver: string,
    assets: bigint,
    shares: bigint,
    feeShares: bigint,
    referralCode: string
  ];
  export interface OutputObject {
    vault: string;
    asset: string;
    sender: string;
    receiver: string;
    assets: bigint;
    shares: bigint;
    feeShares: bigint;
    referralCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRecipientPendingEvent {
  export type InputTuple = [
    vault: AddressLike,
    pendingDepositRecipient: AddressLike
  ];
  export type OutputTuple = [vault: string, pendingDepositRecipient: string];
  export interface OutputObject {
    vault: string;
    pendingDepositRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRecipientUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldDepositRecipient: AddressLike,
    newDepositRecipient: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldDepositRecipient: string,
    newDepositRecipient: string
  ];
  export interface OutputObject {
    vault: string;
    oldDepositRecipient: string;
    newDepositRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeatureDisabledEvent {
  export type InputTuple = [vault: AddressLike, featureId: BytesLike];
  export type OutputTuple = [vault: string, featureId: string];
  export interface OutputObject {
    vault: string;
    featureId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeatureEnabledEvent {
  export type InputTuple = [vault: AddressLike, featureId: BytesLike];
  export type OutputTuple = [vault: string, featureId: string];
  export interface OutputObject {
    vault: string;
    featureId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeatureInitializedEvent {
  export type InputTuple = [vault: AddressLike, featureId: BytesLike];
  export type OutputTuple = [vault: string, featureId: string];
  export interface OutputObject {
    vault: string;
    featureId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceiverPendingEvent {
  export type InputTuple = [
    vault: AddressLike,
    pendingFeeReceiver: AddressLike
  ];
  export type OutputTuple = [vault: string, pendingFeeReceiver: string];
  export interface OutputObject {
    vault: string;
    pendingFeeReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceiverUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldFeeReceiver: AddressLike,
    newFeeReceiver: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldFeeReceiver: string,
    newFeeReceiver: string
  ];
  export interface OutputObject {
    vault: string;
    oldFeeReceiver: string;
    newFeeReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeTransferredEvent {
  export type InputTuple = [
    vault: AddressLike,
    feeReceiver: AddressLike,
    feeShares: BigNumberish,
    feeType: BigNumberish,
    asset: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    feeReceiver: string,
    feeShares: bigint,
    feeType: bigint,
    asset: string
  ];
  export interface OutputObject {
    vault: string;
    feeReceiver: string;
    feeShares: bigint;
    feeType: bigint;
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesClawedBackEvent {
  export type InputTuple = [
    vault: AddressLike,
    feeType: BigNumberish,
    treasury: AddressLike,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    feeType: bigint,
    treasury: string,
    shares: bigint
  ];
  export interface OutputObject {
    vault: string;
    feeType: bigint;
    treasury: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxNavChangePercentUpdatedEvent {
  export type InputTuple = [maxNavChangePercent: BigNumberish];
  export type OutputTuple = [maxNavChangePercent: bigint];
  export interface OutputObject {
    maxNavChangePercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NAVUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    newNav: BigNumberish,
    vestingEndTime: BigNumberish,
    managementFee: BigNumberish,
    performanceFee: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    newNav: bigint,
    vestingEndTime: bigint,
    managementFee: bigint,
    performanceFee: bigint
  ];
  export interface OutputObject {
    vault: string;
    newNav: bigint;
    vestingEndTime: bigint;
    managementFee: bigint;
    performanceFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameAndSymbolUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldName: string,
    oldSymbol: string,
    newName: string,
    newSymbol: string
  ];
  export type OutputTuple = [
    vault: string,
    oldName: string,
    oldSymbol: string,
    newName: string,
    newSymbol: string
  ];
  export interface OutputObject {
    vault: string;
    oldName: string;
    oldSymbol: string;
    newName: string;
    newSymbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceOracleSetEvent {
  export type InputTuple = [priceOracle: AddressLike];
  export type OutputTuple = [priceOracle: string];
  export interface OutputObject {
    priceOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionCancelledEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    queueIndex: BigNumberish
  ];
  export type OutputTuple = [vault: string, user: string, queueIndex: bigint];
  export interface OutputObject {
    vault: string;
    user: string;
    queueIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionEnabledEvent {
  export type InputTuple = [vault: AddressLike, enabled: boolean];
  export type OutputTuple = [vault: string, enabled: boolean];
  export interface OutputObject {
    vault: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionProcessedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    receiver: AddressLike,
    queueIndex: BigNumberish,
    assets: BigNumberish,
    effectiveNav: BigNumberish,
    burnShares: BigNumberish,
    gasFeeShares: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    user: string,
    receiver: string,
    queueIndex: bigint,
    assets: bigint,
    effectiveNav: bigint,
    burnShares: bigint,
    gasFeeShares: bigint
  ];
  export interface OutputObject {
    vault: string;
    user: string;
    receiver: string;
    queueIndex: bigint;
    assets: bigint;
    effectiveNav: bigint;
    burnShares: bigint;
    gasFeeShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionRequestedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    queueIndex: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    user: string,
    queueIndex: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    vault: string;
    user: string;
    queueIndex: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionSourceUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    oldRedemptionSource: AddressLike,
    newRedemptionSource: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    oldRedemptionSource: string,
    newRedemptionSource: string
  ];
  export interface OutputObject {
    vault: string;
    oldRedemptionSource: string;
    newRedemptionSource: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesLockedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [vault: string, user: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesUnlockedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [vault: string, user: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensRescuedEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionFeeStoredEvent {
  export type InputTuple = [
    vault: AddressLike,
    shares: BigNumberish,
    totalStored: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    shares: bigint,
    totalStored: bigint
  ];
  export interface OutputObject {
    vault: string;
    shares: bigint;
    totalStored: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionFeesWithdrawnEvent {
  export type InputTuple = [
    vault: AddressLike,
    recipient: AddressLike,
    transactionFeeShares: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    recipient: string,
    transactionFeeShares: bigint
  ];
  export interface OutputObject {
    vault: string;
    recipient: string;
    transactionFeeShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryPendingEvent {
  export type InputTuple = [pendingTreasury: AddressLike];
  export type OutputTuple = [pendingTreasury: string];
  export interface OutputObject {
    pendingTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultFeesConfiguredEvent {
  export type InputTuple = [
    vault: AddressLike,
    managementFee: BigNumberish,
    performanceFee: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    managementFee: bigint,
    performanceFee: bigint
  ];
  export interface OutputObject {
    vault: string;
    managementFee: bigint;
    performanceFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultPausedEvent {
  export type InputTuple = [vault: AddressLike, curator: AddressLike];
  export type OutputTuple = [vault: string, curator: string];
  export interface OutputObject {
    vault: string;
    curator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultRegisteredEvent {
  export type InputTuple = [
    vault: AddressLike,
    depositRecipient: AddressLike,
    redemptionSource: AddressLike,
    feeReceiver: AddressLike,
    curator: AddressLike,
    baseAsset: AddressLike,
    managementFee: BigNumberish,
    performanceFee: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    depositRecipient: string,
    redemptionSource: string,
    feeReceiver: string,
    curator: string,
    baseAsset: string,
    managementFee: bigint,
    performanceFee: bigint
  ];
  export interface OutputObject {
    vault: string;
    depositRecipient: string;
    redemptionSource: string;
    feeReceiver: string;
    curator: string;
    baseAsset: string;
    managementFee: bigint;
    performanceFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUnpausedEvent {
  export type InputTuple = [vault: AddressLike, operator: AddressLike];
  export type OutputTuple = [vault: string, operator: string];
  export interface OutputObject {
    vault: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUnregisteredEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Vault extends BaseContract {
  connect(runner?: ContractRunner | null): Vault;
  waitForDeployment(): Promise<this>;

  interface: VaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  administrator: TypedContractMethod<[], [string], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  approveManager: TypedContractMethod<[], [void], "nonpayable">;

  asset: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  burn: TypedContractMethod<
    [from: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  convertToAssets: TypedContractMethod<
    [shares: BigNumberish],
    [bigint],
    "view"
  >;

  convertToShares: TypedContractMethod<
    [assets: BigNumberish],
    [bigint],
    "view"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [assets: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getCCIPAdmin: TypedContractMethod<[], [string], "view">;

  getRate: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [
      name_: string,
      symbol_: string,
      administrator_: AddressLike,
      manager_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isBlacklisted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  latestRoundData: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        answer: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;

  lockShares: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockedShares: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  manager: TypedContractMethod<[], [string], "view">;

  maxDeposit: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxRedeem: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  mint: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  previewDeposit: TypedContractMethod<[assets: BigNumberish], [bigint], "view">;

  previewMint: TypedContractMethod<[shares: BigNumberish], [bigint], "view">;

  previewRedeem: TypedContractMethod<[shares: BigNumberish], [bigint], "view">;

  previewWithdraw: TypedContractMethod<
    [assets: BigNumberish],
    [bigint],
    "view"
  >;

  rescueTokens: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAdministrator: TypedContractMethod<
    [_administrator: AddressLike],
    [void],
    "nonpayable"
  >;

  setNameAndSymbol: TypedContractMethod<
    [newName: string, newSymbol: string],
    [void],
    "nonpayable"
  >;

  spendAllowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  unlockShares: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "administrator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveManager"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [from: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "convertToAssets"
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertToShares"
  ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [assets: BigNumberish, receiver: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCCIPAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      name_: string,
      symbol_: string,
      administrator_: AddressLike,
      manager_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "latestRoundData"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        answer: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockShares"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockedShares"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "manager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxDeposit"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxRedeem"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "previewDeposit"
  ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewMint"
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewRedeem"
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewWithdraw"
  ): TypedContractMethod<[assets: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "rescueTokens"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdministrator"
  ): TypedContractMethod<[_administrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNameAndSymbol"
  ): TypedContractMethod<
    [newName: string, newSymbol: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "spendAllowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockShares"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdministratorSet"
  ): TypedContractEvent<
    AdministratorSetEvent.InputTuple,
    AdministratorSetEvent.OutputTuple,
    AdministratorSetEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "AssetFeeConfigUpdated"
  ): TypedContractEvent<
    AssetFeeConfigUpdatedEvent.InputTuple,
    AssetFeeConfigUpdatedEvent.OutputTuple,
    AssetFeeConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AssetWhitelisted"
  ): TypedContractEvent<
    AssetWhitelistedEvent.InputTuple,
    AssetWhitelistedEvent.OutputTuple,
    AssetWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "BaseAssetUpdated"
  ): TypedContractEvent<
    BaseAssetUpdatedEvent.InputTuple,
    BaseAssetUpdatedEvent.OutputTuple,
    BaseAssetUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractsSet"
  ): TypedContractEvent<
    ContractsSetEvent.InputTuple,
    ContractsSetEvent.OutputTuple,
    ContractsSetEvent.OutputObject
  >;
  getEvent(
    key: "CuratorUpdated"
  ): TypedContractEvent<
    CuratorUpdatedEvent.InputTuple,
    CuratorUpdatedEvent.OutputTuple,
    CuratorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "DepositRecipientPending"
  ): TypedContractEvent<
    DepositRecipientPendingEvent.InputTuple,
    DepositRecipientPendingEvent.OutputTuple,
    DepositRecipientPendingEvent.OutputObject
  >;
  getEvent(
    key: "DepositRecipientUpdated"
  ): TypedContractEvent<
    DepositRecipientUpdatedEvent.InputTuple,
    DepositRecipientUpdatedEvent.OutputTuple,
    DepositRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeatureDisabled"
  ): TypedContractEvent<
    FeatureDisabledEvent.InputTuple,
    FeatureDisabledEvent.OutputTuple,
    FeatureDisabledEvent.OutputObject
  >;
  getEvent(
    key: "FeatureEnabled"
  ): TypedContractEvent<
    FeatureEnabledEvent.InputTuple,
    FeatureEnabledEvent.OutputTuple,
    FeatureEnabledEvent.OutputObject
  >;
  getEvent(
    key: "FeatureInitialized"
  ): TypedContractEvent<
    FeatureInitializedEvent.InputTuple,
    FeatureInitializedEvent.OutputTuple,
    FeatureInitializedEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceiverPending"
  ): TypedContractEvent<
    FeeReceiverPendingEvent.InputTuple,
    FeeReceiverPendingEvent.OutputTuple,
    FeeReceiverPendingEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceiverUpdated"
  ): TypedContractEvent<
    FeeReceiverUpdatedEvent.InputTuple,
    FeeReceiverUpdatedEvent.OutputTuple,
    FeeReceiverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeTransferred"
  ): TypedContractEvent<
    FeeTransferredEvent.InputTuple,
    FeeTransferredEvent.OutputTuple,
    FeeTransferredEvent.OutputObject
  >;
  getEvent(
    key: "FeesClawedBack"
  ): TypedContractEvent<
    FeesClawedBackEvent.InputTuple,
    FeesClawedBackEvent.OutputTuple,
    FeesClawedBackEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MaxNavChangePercentUpdated"
  ): TypedContractEvent<
    MaxNavChangePercentUpdatedEvent.InputTuple,
    MaxNavChangePercentUpdatedEvent.OutputTuple,
    MaxNavChangePercentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NAVUpdated"
  ): TypedContractEvent<
    NAVUpdatedEvent.InputTuple,
    NAVUpdatedEvent.OutputTuple,
    NAVUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NameAndSymbolUpdated"
  ): TypedContractEvent<
    NameAndSymbolUpdatedEvent.InputTuple,
    NameAndSymbolUpdatedEvent.OutputTuple,
    NameAndSymbolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PriceOracleSet"
  ): TypedContractEvent<
    PriceOracleSetEvent.InputTuple,
    PriceOracleSetEvent.OutputTuple,
    PriceOracleSetEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionCancelled"
  ): TypedContractEvent<
    RedemptionCancelledEvent.InputTuple,
    RedemptionCancelledEvent.OutputTuple,
    RedemptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionEnabled"
  ): TypedContractEvent<
    RedemptionEnabledEvent.InputTuple,
    RedemptionEnabledEvent.OutputTuple,
    RedemptionEnabledEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionProcessed"
  ): TypedContractEvent<
    RedemptionProcessedEvent.InputTuple,
    RedemptionProcessedEvent.OutputTuple,
    RedemptionProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionRequested"
  ): TypedContractEvent<
    RedemptionRequestedEvent.InputTuple,
    RedemptionRequestedEvent.OutputTuple,
    RedemptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionSourceUpdated"
  ): TypedContractEvent<
    RedemptionSourceUpdatedEvent.InputTuple,
    RedemptionSourceUpdatedEvent.OutputTuple,
    RedemptionSourceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SharesLocked"
  ): TypedContractEvent<
    SharesLockedEvent.InputTuple,
    SharesLockedEvent.OutputTuple,
    SharesLockedEvent.OutputObject
  >;
  getEvent(
    key: "SharesUnlocked"
  ): TypedContractEvent<
    SharesUnlockedEvent.InputTuple,
    SharesUnlockedEvent.OutputTuple,
    SharesUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "TokensRescued"
  ): TypedContractEvent<
    TokensRescuedEvent.InputTuple,
    TokensRescuedEvent.OutputTuple,
    TokensRescuedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionFeeStored"
  ): TypedContractEvent<
    TransactionFeeStoredEvent.InputTuple,
    TransactionFeeStoredEvent.OutputTuple,
    TransactionFeeStoredEvent.OutputObject
  >;
  getEvent(
    key: "TransactionFeesWithdrawn"
  ): TypedContractEvent<
    TransactionFeesWithdrawnEvent.InputTuple,
    TransactionFeesWithdrawnEvent.OutputTuple,
    TransactionFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryPending"
  ): TypedContractEvent<
    TreasuryPendingEvent.InputTuple,
    TreasuryPendingEvent.OutputTuple,
    TreasuryPendingEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultFeesConfigured"
  ): TypedContractEvent<
    VaultFeesConfiguredEvent.InputTuple,
    VaultFeesConfiguredEvent.OutputTuple,
    VaultFeesConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "VaultPaused"
  ): TypedContractEvent<
    VaultPausedEvent.InputTuple,
    VaultPausedEvent.OutputTuple,
    VaultPausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultRegistered"
  ): TypedContractEvent<
    VaultRegisteredEvent.InputTuple,
    VaultRegisteredEvent.OutputTuple,
    VaultRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VaultUnpaused"
  ): TypedContractEvent<
    VaultUnpausedEvent.InputTuple,
    VaultUnpausedEvent.OutputTuple,
    VaultUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultUnregistered"
  ): TypedContractEvent<
    VaultUnregisteredEvent.InputTuple,
    VaultUnregisteredEvent.OutputTuple,
    VaultUnregisteredEvent.OutputObject
  >;

  filters: {
    "AdministratorSet(address,address)": TypedContractEvent<
      AdministratorSetEvent.InputTuple,
      AdministratorSetEvent.OutputTuple,
      AdministratorSetEvent.OutputObject
    >;
    AdministratorSet: TypedContractEvent<
      AdministratorSetEvent.InputTuple,
      AdministratorSetEvent.OutputTuple,
      AdministratorSetEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "AssetFeeConfigUpdated(address,address,uint256,uint256)": TypedContractEvent<
      AssetFeeConfigUpdatedEvent.InputTuple,
      AssetFeeConfigUpdatedEvent.OutputTuple,
      AssetFeeConfigUpdatedEvent.OutputObject
    >;
    AssetFeeConfigUpdated: TypedContractEvent<
      AssetFeeConfigUpdatedEvent.InputTuple,
      AssetFeeConfigUpdatedEvent.OutputTuple,
      AssetFeeConfigUpdatedEvent.OutputObject
    >;

    "AssetWhitelisted(address,address,bool)": TypedContractEvent<
      AssetWhitelistedEvent.InputTuple,
      AssetWhitelistedEvent.OutputTuple,
      AssetWhitelistedEvent.OutputObject
    >;
    AssetWhitelisted: TypedContractEvent<
      AssetWhitelistedEvent.InputTuple,
      AssetWhitelistedEvent.OutputTuple,
      AssetWhitelistedEvent.OutputObject
    >;

    "BaseAssetUpdated(address,address,address)": TypedContractEvent<
      BaseAssetUpdatedEvent.InputTuple,
      BaseAssetUpdatedEvent.OutputTuple,
      BaseAssetUpdatedEvent.OutputObject
    >;
    BaseAssetUpdated: TypedContractEvent<
      BaseAssetUpdatedEvent.InputTuple,
      BaseAssetUpdatedEvent.OutputTuple,
      BaseAssetUpdatedEvent.OutputObject
    >;

    "ContractsSet(address,address,address,address)": TypedContractEvent<
      ContractsSetEvent.InputTuple,
      ContractsSetEvent.OutputTuple,
      ContractsSetEvent.OutputObject
    >;
    ContractsSet: TypedContractEvent<
      ContractsSetEvent.InputTuple,
      ContractsSetEvent.OutputTuple,
      ContractsSetEvent.OutputObject
    >;

    "CuratorUpdated(address,address,address)": TypedContractEvent<
      CuratorUpdatedEvent.InputTuple,
      CuratorUpdatedEvent.OutputTuple,
      CuratorUpdatedEvent.OutputObject
    >;
    CuratorUpdated: TypedContractEvent<
      CuratorUpdatedEvent.InputTuple,
      CuratorUpdatedEvent.OutputTuple,
      CuratorUpdatedEvent.OutputObject
    >;

    "Deposit(address,address,address,address,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "DepositRecipientPending(address,address)": TypedContractEvent<
      DepositRecipientPendingEvent.InputTuple,
      DepositRecipientPendingEvent.OutputTuple,
      DepositRecipientPendingEvent.OutputObject
    >;
    DepositRecipientPending: TypedContractEvent<
      DepositRecipientPendingEvent.InputTuple,
      DepositRecipientPendingEvent.OutputTuple,
      DepositRecipientPendingEvent.OutputObject
    >;

    "DepositRecipientUpdated(address,address,address)": TypedContractEvent<
      DepositRecipientUpdatedEvent.InputTuple,
      DepositRecipientUpdatedEvent.OutputTuple,
      DepositRecipientUpdatedEvent.OutputObject
    >;
    DepositRecipientUpdated: TypedContractEvent<
      DepositRecipientUpdatedEvent.InputTuple,
      DepositRecipientUpdatedEvent.OutputTuple,
      DepositRecipientUpdatedEvent.OutputObject
    >;

    "FeatureDisabled(address,bytes32)": TypedContractEvent<
      FeatureDisabledEvent.InputTuple,
      FeatureDisabledEvent.OutputTuple,
      FeatureDisabledEvent.OutputObject
    >;
    FeatureDisabled: TypedContractEvent<
      FeatureDisabledEvent.InputTuple,
      FeatureDisabledEvent.OutputTuple,
      FeatureDisabledEvent.OutputObject
    >;

    "FeatureEnabled(address,bytes32)": TypedContractEvent<
      FeatureEnabledEvent.InputTuple,
      FeatureEnabledEvent.OutputTuple,
      FeatureEnabledEvent.OutputObject
    >;
    FeatureEnabled: TypedContractEvent<
      FeatureEnabledEvent.InputTuple,
      FeatureEnabledEvent.OutputTuple,
      FeatureEnabledEvent.OutputObject
    >;

    "FeatureInitialized(address,bytes32)": TypedContractEvent<
      FeatureInitializedEvent.InputTuple,
      FeatureInitializedEvent.OutputTuple,
      FeatureInitializedEvent.OutputObject
    >;
    FeatureInitialized: TypedContractEvent<
      FeatureInitializedEvent.InputTuple,
      FeatureInitializedEvent.OutputTuple,
      FeatureInitializedEvent.OutputObject
    >;

    "FeeReceiverPending(address,address)": TypedContractEvent<
      FeeReceiverPendingEvent.InputTuple,
      FeeReceiverPendingEvent.OutputTuple,
      FeeReceiverPendingEvent.OutputObject
    >;
    FeeReceiverPending: TypedContractEvent<
      FeeReceiverPendingEvent.InputTuple,
      FeeReceiverPendingEvent.OutputTuple,
      FeeReceiverPendingEvent.OutputObject
    >;

    "FeeReceiverUpdated(address,address,address)": TypedContractEvent<
      FeeReceiverUpdatedEvent.InputTuple,
      FeeReceiverUpdatedEvent.OutputTuple,
      FeeReceiverUpdatedEvent.OutputObject
    >;
    FeeReceiverUpdated: TypedContractEvent<
      FeeReceiverUpdatedEvent.InputTuple,
      FeeReceiverUpdatedEvent.OutputTuple,
      FeeReceiverUpdatedEvent.OutputObject
    >;

    "FeeTransferred(address,address,uint256,uint8,address)": TypedContractEvent<
      FeeTransferredEvent.InputTuple,
      FeeTransferredEvent.OutputTuple,
      FeeTransferredEvent.OutputObject
    >;
    FeeTransferred: TypedContractEvent<
      FeeTransferredEvent.InputTuple,
      FeeTransferredEvent.OutputTuple,
      FeeTransferredEvent.OutputObject
    >;

    "FeesClawedBack(address,uint8,address,uint256)": TypedContractEvent<
      FeesClawedBackEvent.InputTuple,
      FeesClawedBackEvent.OutputTuple,
      FeesClawedBackEvent.OutputObject
    >;
    FeesClawedBack: TypedContractEvent<
      FeesClawedBackEvent.InputTuple,
      FeesClawedBackEvent.OutputTuple,
      FeesClawedBackEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MaxNavChangePercentUpdated(uint256)": TypedContractEvent<
      MaxNavChangePercentUpdatedEvent.InputTuple,
      MaxNavChangePercentUpdatedEvent.OutputTuple,
      MaxNavChangePercentUpdatedEvent.OutputObject
    >;
    MaxNavChangePercentUpdated: TypedContractEvent<
      MaxNavChangePercentUpdatedEvent.InputTuple,
      MaxNavChangePercentUpdatedEvent.OutputTuple,
      MaxNavChangePercentUpdatedEvent.OutputObject
    >;

    "NAVUpdated(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      NAVUpdatedEvent.InputTuple,
      NAVUpdatedEvent.OutputTuple,
      NAVUpdatedEvent.OutputObject
    >;
    NAVUpdated: TypedContractEvent<
      NAVUpdatedEvent.InputTuple,
      NAVUpdatedEvent.OutputTuple,
      NAVUpdatedEvent.OutputObject
    >;

    "NameAndSymbolUpdated(address,string,string,string,string)": TypedContractEvent<
      NameAndSymbolUpdatedEvent.InputTuple,
      NameAndSymbolUpdatedEvent.OutputTuple,
      NameAndSymbolUpdatedEvent.OutputObject
    >;
    NameAndSymbolUpdated: TypedContractEvent<
      NameAndSymbolUpdatedEvent.InputTuple,
      NameAndSymbolUpdatedEvent.OutputTuple,
      NameAndSymbolUpdatedEvent.OutputObject
    >;

    "PriceOracleSet(address)": TypedContractEvent<
      PriceOracleSetEvent.InputTuple,
      PriceOracleSetEvent.OutputTuple,
      PriceOracleSetEvent.OutputObject
    >;
    PriceOracleSet: TypedContractEvent<
      PriceOracleSetEvent.InputTuple,
      PriceOracleSetEvent.OutputTuple,
      PriceOracleSetEvent.OutputObject
    >;

    "RedemptionCancelled(address,address,uint256)": TypedContractEvent<
      RedemptionCancelledEvent.InputTuple,
      RedemptionCancelledEvent.OutputTuple,
      RedemptionCancelledEvent.OutputObject
    >;
    RedemptionCancelled: TypedContractEvent<
      RedemptionCancelledEvent.InputTuple,
      RedemptionCancelledEvent.OutputTuple,
      RedemptionCancelledEvent.OutputObject
    >;

    "RedemptionEnabled(address,bool)": TypedContractEvent<
      RedemptionEnabledEvent.InputTuple,
      RedemptionEnabledEvent.OutputTuple,
      RedemptionEnabledEvent.OutputObject
    >;
    RedemptionEnabled: TypedContractEvent<
      RedemptionEnabledEvent.InputTuple,
      RedemptionEnabledEvent.OutputTuple,
      RedemptionEnabledEvent.OutputObject
    >;

    "RedemptionProcessed(address,address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RedemptionProcessedEvent.InputTuple,
      RedemptionProcessedEvent.OutputTuple,
      RedemptionProcessedEvent.OutputObject
    >;
    RedemptionProcessed: TypedContractEvent<
      RedemptionProcessedEvent.InputTuple,
      RedemptionProcessedEvent.OutputTuple,
      RedemptionProcessedEvent.OutputObject
    >;

    "RedemptionRequested(address,address,uint256,uint256)": TypedContractEvent<
      RedemptionRequestedEvent.InputTuple,
      RedemptionRequestedEvent.OutputTuple,
      RedemptionRequestedEvent.OutputObject
    >;
    RedemptionRequested: TypedContractEvent<
      RedemptionRequestedEvent.InputTuple,
      RedemptionRequestedEvent.OutputTuple,
      RedemptionRequestedEvent.OutputObject
    >;

    "RedemptionSourceUpdated(address,address,address)": TypedContractEvent<
      RedemptionSourceUpdatedEvent.InputTuple,
      RedemptionSourceUpdatedEvent.OutputTuple,
      RedemptionSourceUpdatedEvent.OutputObject
    >;
    RedemptionSourceUpdated: TypedContractEvent<
      RedemptionSourceUpdatedEvent.InputTuple,
      RedemptionSourceUpdatedEvent.OutputTuple,
      RedemptionSourceUpdatedEvent.OutputObject
    >;

    "SharesLocked(address,address,uint256)": TypedContractEvent<
      SharesLockedEvent.InputTuple,
      SharesLockedEvent.OutputTuple,
      SharesLockedEvent.OutputObject
    >;
    SharesLocked: TypedContractEvent<
      SharesLockedEvent.InputTuple,
      SharesLockedEvent.OutputTuple,
      SharesLockedEvent.OutputObject
    >;

    "SharesUnlocked(address,address,uint256)": TypedContractEvent<
      SharesUnlockedEvent.InputTuple,
      SharesUnlockedEvent.OutputTuple,
      SharesUnlockedEvent.OutputObject
    >;
    SharesUnlocked: TypedContractEvent<
      SharesUnlockedEvent.InputTuple,
      SharesUnlockedEvent.OutputTuple,
      SharesUnlockedEvent.OutputObject
    >;

    "TokensRescued(address,address,uint256)": TypedContractEvent<
      TokensRescuedEvent.InputTuple,
      TokensRescuedEvent.OutputTuple,
      TokensRescuedEvent.OutputObject
    >;
    TokensRescued: TypedContractEvent<
      TokensRescuedEvent.InputTuple,
      TokensRescuedEvent.OutputTuple,
      TokensRescuedEvent.OutputObject
    >;

    "TransactionFeeStored(address,uint256,uint256)": TypedContractEvent<
      TransactionFeeStoredEvent.InputTuple,
      TransactionFeeStoredEvent.OutputTuple,
      TransactionFeeStoredEvent.OutputObject
    >;
    TransactionFeeStored: TypedContractEvent<
      TransactionFeeStoredEvent.InputTuple,
      TransactionFeeStoredEvent.OutputTuple,
      TransactionFeeStoredEvent.OutputObject
    >;

    "TransactionFeesWithdrawn(address,address,uint256)": TypedContractEvent<
      TransactionFeesWithdrawnEvent.InputTuple,
      TransactionFeesWithdrawnEvent.OutputTuple,
      TransactionFeesWithdrawnEvent.OutputObject
    >;
    TransactionFeesWithdrawn: TypedContractEvent<
      TransactionFeesWithdrawnEvent.InputTuple,
      TransactionFeesWithdrawnEvent.OutputTuple,
      TransactionFeesWithdrawnEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "TreasuryPending(address)": TypedContractEvent<
      TreasuryPendingEvent.InputTuple,
      TreasuryPendingEvent.OutputTuple,
      TreasuryPendingEvent.OutputObject
    >;
    TreasuryPending: TypedContractEvent<
      TreasuryPendingEvent.InputTuple,
      TreasuryPendingEvent.OutputTuple,
      TreasuryPendingEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "VaultFeesConfigured(address,uint256,uint256)": TypedContractEvent<
      VaultFeesConfiguredEvent.InputTuple,
      VaultFeesConfiguredEvent.OutputTuple,
      VaultFeesConfiguredEvent.OutputObject
    >;
    VaultFeesConfigured: TypedContractEvent<
      VaultFeesConfiguredEvent.InputTuple,
      VaultFeesConfiguredEvent.OutputTuple,
      VaultFeesConfiguredEvent.OutputObject
    >;

    "VaultPaused(address,address)": TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;
    VaultPaused: TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;

    "VaultRegistered(address,address,address,address,address,address,uint256,uint256)": TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;
    VaultRegistered: TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;

    "VaultUnpaused(address,address)": TypedContractEvent<
      VaultUnpausedEvent.InputTuple,
      VaultUnpausedEvent.OutputTuple,
      VaultUnpausedEvent.OutputObject
    >;
    VaultUnpaused: TypedContractEvent<
      VaultUnpausedEvent.InputTuple,
      VaultUnpausedEvent.OutputTuple,
      VaultUnpausedEvent.OutputObject
    >;

    "VaultUnregistered(address)": TypedContractEvent<
      VaultUnregisteredEvent.InputTuple,
      VaultUnregisteredEvent.OutputTuple,
      VaultUnregisteredEvent.OutputObject
    >;
    VaultUnregistered: TypedContractEvent<
      VaultUnregisteredEvent.InputTuple,
      VaultUnregisteredEvent.OutputTuple,
      VaultUnregisteredEvent.OutputObject
    >;
  };
}
